using Hyka.Service.TerritoryDto;

namespace Hyka.Models
{
    public class Territory
    {
        public String DepartmentId { get; set; }
        public String MunicipalityId { get; set; }
        public String DepartmentName { get; set; }
        public String MunicipalityName { get; set; }

        public static readonly List<TerritoryRecord> territories = new()
        {
            new TerritoryRecord("", "", "ERROR 404", "ERROR 404"),
            new TerritoryRecord("01", "001", "ANTIOQUIA", "MEDELLIN"),
            new TerritoryRecord("01", "004", "ANTIOQUIA", "ABEJORRAL"),
            new TerritoryRecord("01", "007", "ANTIOQUIA", "ABRIAQUI"),
            new TerritoryRecord("01", "010", "ANTIOQUIA", "ALEJANDRIA"),
            new TerritoryRecord("01", "013", "ANTIOQUIA", "AMAGA"),
            new TerritoryRecord("01", "016", "ANTIOQUIA", "AMALFI"),
            new TerritoryRecord("01", "019", "ANTIOQUIA", "ANDES"),
            new TerritoryRecord("01", "022", "ANTIOQUIA", "ANGELOPOLIS"),
            new TerritoryRecord("01", "025", "ANTIOQUIA", "ANGOSTURA"),
            new TerritoryRecord("01", "028", "ANTIOQUIA", "ANORI"),
            new TerritoryRecord("01", "031", "ANTIOQUIA", "ANTIOQUIA"),
            new TerritoryRecord("01", "034", "ANTIOQUIA", "ANZA"),
            new TerritoryRecord("01", "035", "ANTIOQUIA", "APARTADO"),
            new TerritoryRecord("01", "037", "ANTIOQUIA", "ARBOLETES"),
            new TerritoryRecord("01", "039", "ANTIOQUIA", "ARGELIA"),
            new TerritoryRecord("01", "040", "ANTIOQUIA", "ARMENIA"),
            new TerritoryRecord("01", "043", "ANTIOQUIA", "BARBOSA"),
            new TerritoryRecord("01", "046", "ANTIOQUIA", "BELMIRA"),
            new TerritoryRecord("01", "049", "ANTIOQUIA", "BELLO"),
            new TerritoryRecord("01", "052", "ANTIOQUIA", "BETANIA"),
            new TerritoryRecord("01", "055", "ANTIOQUIA", "BETULIA"),
            new TerritoryRecord("01", "058", "ANTIOQUIA", "BOLIVAR"),
            new TerritoryRecord("01", "061", "ANTIOQUIA", "BURITICA"),
            new TerritoryRecord("01", "062", "ANTIOQUIA", "BRICE/O"),
            new TerritoryRecord("01", "064", "ANTIOQUIA", "CACERES"),
            new TerritoryRecord("01", "067", "ANTIOQUIA", "CAICEDO"),
            new TerritoryRecord("01", "070", "ANTIOQUIA", "CALDAS"),
            new TerritoryRecord("01", "073", "ANTIOQUIA", "CAMPAMENTO"),
            new TerritoryRecord("01", "076", "ANTIOQUIA", "CA/ASGORDAS"),
            new TerritoryRecord("01", "078", "ANTIOQUIA", "CARACOLI"),
            new TerritoryRecord("01", "079", "ANTIOQUIA", "CARAMANTA"),
            new TerritoryRecord("01", "080", "ANTIOQUIA", "CAREPA"),
            new TerritoryRecord("01", "082", "ANTIOQUIA", "CARMEN DE VIBORAL"),
            new TerritoryRecord("01", "085", "ANTIOQUIA", "CAROLINA"),
            new TerritoryRecord("01", "088", "ANTIOQUIA", "CAUCASIA"),
            new TerritoryRecord("01", "091", "ANTIOQUIA", "CISNEROS"),
            new TerritoryRecord("01", "094", "ANTIOQUIA", "COCORNA"),
            new TerritoryRecord("01", "097", "ANTIOQUIA", "CONCEPCION"),
            new TerritoryRecord("01", "100", "ANTIOQUIA", "CONCORDIA"),
            new TerritoryRecord("01", "103", "ANTIOQUIA", "COPACABANA"),
            new TerritoryRecord("01", "106", "ANTIOQUIA", "CHIGORODO"),
            new TerritoryRecord("01", "109", "ANTIOQUIA", "DABEIBA"),
            new TerritoryRecord("01", "112", "ANTIOQUIA", "DON MATIAS"),
            new TerritoryRecord("01", "115", "ANTIOQUIA", "EBEJICO"),
            new TerritoryRecord("01", "117", "ANTIOQUIA", "EL BAGRE"),
            new TerritoryRecord("01", "118", "ANTIOQUIA", "ENTRERRIOS"),
            new TerritoryRecord("01", "121", "ANTIOQUIA", "ENVIGADO"),
            new TerritoryRecord("01", "124", "ANTIOQUIA", "FREDONIA"),
            new TerritoryRecord("01", "127", "ANTIOQUIA", "FRONTINO"),
            new TerritoryRecord("01", "130", "ANTIOQUIA", "GIRALDO"),
            new TerritoryRecord("01", "133", "ANTIOQUIA", "GIRARDOTA"),
            new TerritoryRecord("01", "136", "ANTIOQUIA", "GOMEZ PLATA"),
            new TerritoryRecord("01", "139", "ANTIOQUIA", "GRANADA"),
            new TerritoryRecord("01", "140", "ANTIOQUIA", "GUADALUPE"),
            new TerritoryRecord("01", "142", "ANTIOQUIA", "GUARNE"),
            new TerritoryRecord("01", "145", "ANTIOQUIA", "GUATAPE"),
            new TerritoryRecord("01", "148", "ANTIOQUIA", "HELICONIA"),
            new TerritoryRecord("01", "150", "ANTIOQUIA", "HISPANIA"),
            new TerritoryRecord("01", "151", "ANTIOQUIA", "ITAGUI"),
            new TerritoryRecord("01", "154", "ANTIOQUIA", "ITUANGO"),
            new TerritoryRecord("01", "157", "ANTIOQUIA", "JARDIN"),
            new TerritoryRecord("01", "160", "ANTIOQUIA", "JERICO"),
            new TerritoryRecord("01", "163", "ANTIOQUIA", "LA CEJA"),
            new TerritoryRecord("01", "166", "ANTIOQUIA", "LA ESTRELLA"),
            new TerritoryRecord("01", "168", "ANTIOQUIA", "PUERTO NARE‐LA MAGDALENA"),
            new TerritoryRecord("01", "169", "ANTIOQUIA", "LA UNION"),
            new TerritoryRecord("01", "170", "ANTIOQUIA", "LA PINTADA"),
            new TerritoryRecord("01", "172", "ANTIOQUIA", "LIBORINA"),
            new TerritoryRecord("01", "175", "ANTIOQUIA", "MACEO"),
            new TerritoryRecord("01", "178", "ANTIOQUIA", "MARINILLA"),
            new TerritoryRecord("01", "181", "ANTIOQUIA", "MONTEBELLO"),
            new TerritoryRecord("01", "184", "ANTIOQUIA", "MURINDO"),
            new TerritoryRecord("01", "187", "ANTIOQUIA", "MUTATA"),
            new TerritoryRecord("01", "190", "ANTIOQUIA", "NARI/O"),
            new TerritoryRecord("01", "191", "ANTIOQUIA", "NECHI"),
            new TerritoryRecord("01", "192", "ANTIOQUIA", "NECOCLI"),
            new TerritoryRecord("01", "193", "ANTIOQUIA", "OLAYA"),
            new TerritoryRecord("01", "196", "ANTIOQUIA", "PE/OL"),
            new TerritoryRecord("01", "199", "ANTIOQUIA", "PEQUE"),
            new TerritoryRecord("01", "202", "ANTIOQUIA", "PUEBLORRICO"),
            new TerritoryRecord("01", "205", "ANTIOQUIA", "PUERTO BERRIO"),
            new TerritoryRecord("01", "206", "ANTIOQUIA", "PUERTO TRIUNFO"),
            new TerritoryRecord("01", "208", "ANTIOQUIA", "REMEDIOS"),
            new TerritoryRecord("01", "211", "ANTIOQUIA", "RETIRO"),
            new TerritoryRecord("01", "214", "ANTIOQUIA", "RIONEGRO"),
            new TerritoryRecord("01", "217", "ANTIOQUIA", "SABANALARGA"),
            new TerritoryRecord("01", "218", "ANTIOQUIA", "SABANETA"),
            new TerritoryRecord("01", "220", "ANTIOQUIA", "SALGAR"),
            new TerritoryRecord("01", "223", "ANTIOQUIA", "SAN ANDRES"),
            new TerritoryRecord("01", "226", "ANTIOQUIA", "SAN CARLOS"),
            new TerritoryRecord("01", "227", "ANTIOQUIA", "SAN FRANCISCO"),
            new TerritoryRecord("01", "229", "ANTIOQUIA", "SAN JERONIMO"),
            new TerritoryRecord("01", "230", "ANTIOQUIA", "SAN JOSE DE LA MONTA/A"),
            new TerritoryRecord("01", "231", "ANTIOQUIA", "SAN JUAN DE URABA"),
            new TerritoryRecord("01", "232", "ANTIOQUIA", "SAN LUIS"),
            new TerritoryRecord("01", "235", "ANTIOQUIA", "SAN PEDRO"),
            new TerritoryRecord("01", "237", "ANTIOQUIA", "SAN PEDRO DE URABA"),
            new TerritoryRecord("01", "238", "ANTIOQUIA", "SAN RAFAEL"),
            new TerritoryRecord("01", "241", "ANTIOQUIA", "SAN ROQUE"),
            new TerritoryRecord("01", "244", "ANTIOQUIA", "SAN VICENTE"),
            new TerritoryRecord("01", "247", "ANTIOQUIA", "SANTA BARBARA"),
            new TerritoryRecord("01", "250", "ANTIOQUIA", "SANTA ROSA DE OSOS"),
            new TerritoryRecord("01", "253", "ANTIOQUIA", "SANTO DOMINGO"),
            new TerritoryRecord("01", "256", "ANTIOQUIA", "SANTUARIO"),
            new TerritoryRecord("01", "259", "ANTIOQUIA", "SEGOVIA"),
            new TerritoryRecord("01", "262", "ANTIOQUIA", "SONSON"),
            new TerritoryRecord("01", "265", "ANTIOQUIA", "SOPETRAN"),
            new TerritoryRecord("01", "268", "ANTIOQUIA", "TAMESIS"),
            new TerritoryRecord("01", "270", "ANTIOQUIA", "TARAZA"),
            new TerritoryRecord("01", "271", "ANTIOQUIA", "TARSO"),
            new TerritoryRecord("01", "274", "ANTIOQUIA", "TITIRIBI"),
            new TerritoryRecord("01", "277", "ANTIOQUIA", "TOLEDO"),
            new TerritoryRecord("01", "280", "ANTIOQUIA", "TURBO"),
            new TerritoryRecord("01", "282", "ANTIOQUIA", "URAMITA"),
            new TerritoryRecord("01", "283", "ANTIOQUIA", "URRAO"),
            new TerritoryRecord("01", "286", "ANTIOQUIA", "VALDIVIA"),
            new TerritoryRecord("01", "289", "ANTIOQUIA", "VALPARAISO"),
            new TerritoryRecord("01", "290", "ANTIOQUIA", "VEGACHI"),
            new TerritoryRecord("01", "291", "ANTIOQUIA", "VIGIA DEL FUERTE"),
            new TerritoryRecord("01", "292", "ANTIOQUIA", "VENECIA"),
            new TerritoryRecord("01", "293", "ANTIOQUIA", "YALI"),
            new TerritoryRecord("01", "295", "ANTIOQUIA", "YARUMAL"),
            new TerritoryRecord("01", "298", "ANTIOQUIA", "YOLOMBO"),
            new TerritoryRecord("01", "300", "ANTIOQUIA", "YONDO‐CASABE"),
            new TerritoryRecord("01", "301", "ANTIOQUIA", "ZARAGOZA"),
            new TerritoryRecord("03", "001", "ATLANTICO", "BARRANQUILLA"),
            new TerritoryRecord("03", "004", "ATLANTICO", "BARANOA"),
            new TerritoryRecord("03", "007", "ATLANTICO", "CAMPO DE LA CRUZ"),
            new TerritoryRecord("03", "010", "ATLANTICO", "CANDELARIA"),
            new TerritoryRecord("03", "013", "ATLANTICO", "GALAPA"),
            new TerritoryRecord("03", "016", "ATLANTICO", "JUAN DE ACOSTA"),
            new TerritoryRecord("03", "019", "ATLANTICO", "LURUACO"),
            new TerritoryRecord("03", "022", "ATLANTICO", "MALAMBO"),
            new TerritoryRecord("03", "025", "ATLANTICO", "MANATI"),
            new TerritoryRecord("03", "028", "ATLANTICO", "PALMAR DE VARELA"),
            new TerritoryRecord("03", "031", "ATLANTICO", "PIOJO"),
            new TerritoryRecord("03", "034", "ATLANTICO", "POLONUEVO"),
            new TerritoryRecord("03", "035", "ATLANTICO", "PONEDERA"),
            new TerritoryRecord("03", "037", "ATLANTICO", "PUERTO COLOMBIA"),
            new TerritoryRecord("03", "040", "ATLANTICO", "REPELON"),
            new TerritoryRecord("03", "043", "ATLANTICO", "SABANAGRANDE"),
            new TerritoryRecord("03", "046", "ATLANTICO", "SABANALARGA"),
            new TerritoryRecord("03", "047", "ATLANTICO", "SANTA LUCIA"),
            new TerritoryRecord("03", "049", "ATLANTICO", "SANTO TOMAS"),
            new TerritoryRecord("03", "052", "ATLANTICO", "SOLEDAD"),
            new TerritoryRecord("03", "055", "ATLANTICO", "SUAN"),
            new TerritoryRecord("03", "058", "ATLANTICO", "TUBARA"),
            new TerritoryRecord("03", "061", "ATLANTICO", "USIACURI"),
            new TerritoryRecord("05", "001", "BOLIVAR", "CARTAGENA"),
            new TerritoryRecord("05", "004", "BOLIVAR", "ACHI"),
            new TerritoryRecord("05", "005", "BOLIVAR", "ARENAL"),
            new TerritoryRecord("05", "006", "BOLIVAR", "ALTOS DEL ROSARIO"),
            new TerritoryRecord("05", "007", "BOLIVAR", "ARJONA"),
            new TerritoryRecord("05", "009", "BOLIVAR", "ARROYO HONDO"),
            new TerritoryRecord("05", "010", "BOLIVAR", "BARRANCO DE LOBA"),
            new TerritoryRecord("05", "013", "BOLIVAR", "CALAMAR"),
            new TerritoryRecord("05", "014", "BOLIVAR", "CANTAGALLO"),
            new TerritoryRecord("05", "015", "BOLIVAR", "CICUCO"),
            new TerritoryRecord("05", "016", "BOLIVAR", "CORDOBA"),
            new TerritoryRecord("05", "018", "BOLIVAR", "CLEMENCIA"),
            new TerritoryRecord("05", "022", "BOLIVAR", "EL CARMEN DE BOLIVAR"),
            new TerritoryRecord("05", "025", "BOLIVAR", "EL GUAMO"),
            new TerritoryRecord("05", "026", "BOLIVAR", "HATILLO DE LOBA"),
            new TerritoryRecord("05", "027", "BOLIVAR", "EL PE/ON"),
            new TerritoryRecord("05", "028", "BOLIVAR", "MAGANGUE"),
            new TerritoryRecord("05", "031", "BOLIVAR", "MAHATES"),
            new TerritoryRecord("05", "037", "BOLIVAR", "MARGARITA"),
            new TerritoryRecord("05", "040", "BOLIVAR", "MARIA LA BAJA"),
            new TerritoryRecord("05", "041", "BOLIVAR", "MONTECRISTO"),
            new TerritoryRecord("05", "043", "BOLIVAR", "MOMPOS"),
            new TerritoryRecord("05", "044", "BOLIVAR", "MORALES"),
            new TerritoryRecord("05", "050", "BOLIVAR", "NOROSI"),
            new TerritoryRecord("05", "059", "BOLIVAR", "PINILLOS"),
            new TerritoryRecord("05", "063", "BOLIVAR", "REGIDOR"),
            new TerritoryRecord("05", "065", "BOLIVAR", "RIOVIEJO"),
            new TerritoryRecord("05", "070", "BOLIVAR", "SAN ESTANISLAO"),
            new TerritoryRecord("05", "072", "BOLIVAR", "SAN CRISTOBAL"),
            new TerritoryRecord("05", "073", "BOLIVAR", "SAN FERNANDO"),
            new TerritoryRecord("05", "076", "BOLIVAR", "SAN JACINTO"),
            new TerritoryRecord("05", "078", "BOLIVAR", "SAN JACINTO DEL CAUCA"),
            new TerritoryRecord("05", "079", "BOLIVAR", "SAN JUAN NEPOMUCENO"),
            new TerritoryRecord("05", "082", "BOLIVAR", "SAN MARTIN DE LOBA"),
            new TerritoryRecord("05", "084", "BOLIVAR", "SAN PABLO"),
            new TerritoryRecord("05", "091", "BOLIVAR", "SANTA CATALINA"),
            new TerritoryRecord("05", "094", "BOLIVAR", "SANTA ROSA"),
            new TerritoryRecord("05", "095", "BOLIVAR", "SANTA ROSA DEL SUR"),
            new TerritoryRecord("05", "097", "BOLIVAR", "SIMITI"),
            new TerritoryRecord("05", "106", "BOLIVAR", "SOPLAVIENTO"),
            new TerritoryRecord("05", "110", "BOLIVAR", "TALAIGUA NUEVO"),
            new TerritoryRecord("05", "113", "BOLIVAR", "TIQUISIO (PTO. RICO)"),
            new TerritoryRecord("05", "118", "BOLIVAR", "TURBACO"),
            new TerritoryRecord("05", "121", "BOLIVAR", "TURBANA"),
            new TerritoryRecord("05", "124", "BOLIVAR", "VILLANUEVA"),
            new TerritoryRecord("05", "127", "BOLIVAR", "ZAMBRANO"),
            new TerritoryRecord("07", "001", "BOYACA", "TUNJA"),
            new TerritoryRecord("07", "007", "BOYACA", "ALMEIDA"),
            new TerritoryRecord("07", "008", "BOYACA", "AQUITANIA (PUEBLOVIEJO)"),
            new TerritoryRecord("07", "010", "BOYACA", "ARCABUCO"),
            new TerritoryRecord("07", "013", "BOYACA", "BELEN"),
            new TerritoryRecord("07", "016", "BOYACA", "BERBEO"),
            new TerritoryRecord("07", "019", "BOYACA", "BETEITIVA"),
            new TerritoryRecord("07", "022", "BOYACA", "BOAVITA"),
            new TerritoryRecord("07", "025", "BOYACA", "BOYACA"),
            new TerritoryRecord("07", "028", "BOYACA", "BRICE/O"),
            new TerritoryRecord("07", "031", "BOYACA", "BUENAVISTA"),
            new TerritoryRecord("07", "034", "BOYACA", "BUSBANZA"),
            new TerritoryRecord("07", "037", "BOYACA", "CALDAS"),
            new TerritoryRecord("07", "040", "BOYACA", "CAMPOHERMOSO"),
            new TerritoryRecord("07", "043", "BOYACA", "CERINZA"),
            new TerritoryRecord("07", "046", "BOYACA", "CIENEGA"),
            new TerritoryRecord("07", "049", "BOYACA", "COMBITA"),
            new TerritoryRecord("07", "052", "BOYACA", "COPER"),
            new TerritoryRecord("07", "055", "BOYACA", "CORRALES"),
            new TerritoryRecord("07", "058", "BOYACA", "COVARACHIA"),
            new TerritoryRecord("07", "059", "BOYACA", "CUBARA"),
            new TerritoryRecord("07", "060", "BOYACA", "CUCAITA"),
            new TerritoryRecord("07", "061", "BOYACA", "CUITIVA"),
            new TerritoryRecord("07", "064", "BOYACA", "CHINAVITA"),
            new TerritoryRecord("07", "067", "BOYACA", "CHIQUINQUIRA"),
            new TerritoryRecord("07", "068", "BOYACA", "CHIQUIZA"),
            new TerritoryRecord("07", "070", "BOYACA", "CHISCAS"),
            new TerritoryRecord("07", "073", "BOYACA", "CHITA"),
            new TerritoryRecord("07", "076", "BOYACA", "CHITARAQUE"),
            new TerritoryRecord("07", "077", "BOYACA", "CHIVATA"),
            new TerritoryRecord("07", "078", "BOYACA", "CHIVOR"),
            new TerritoryRecord("07", "079", "BOYACA", "DUITAMA"),
            new TerritoryRecord("07", "082", "BOYACA", "EL COCUY"),
            new TerritoryRecord("07", "085", "BOYACA", "EL ESPINO"),
            new TerritoryRecord("07", "088", "BOYACA", "FIRAVITOBA"),
            new TerritoryRecord("07", "091", "BOYACA", "FLORESTA"),
            new TerritoryRecord("07", "094", "BOYACA", "GACHANTIVA"),
            new TerritoryRecord("07", "097", "BOYACA", "GAMEZA"),
            new TerritoryRecord("07", "100", "BOYACA", "GARAGOA"),
            new TerritoryRecord("07", "103", "BOYACA", "GUACAMAYAS"),
            new TerritoryRecord("07", "106", "BOYACA", "GUATEQUE"),
            new TerritoryRecord("07", "109", "BOYACA", "GUAYATA"),
            new TerritoryRecord("07", "112", "BOYACA", "GUICAN"),
            new TerritoryRecord("07", "118", "BOYACA", "IZA"),
            new TerritoryRecord("07", "121", "BOYACA", "JENESANO"),
            new TerritoryRecord("07", "124", "BOYACA", "JERICO"),
            new TerritoryRecord("07", "127", "BOYACA", "LABRANZAGRANDE"),
            new TerritoryRecord("07", "130", "BOYACA", "LA CAPILLA"),
            new TerritoryRecord("07", "136", "BOYACA", "LA UVITA"),
            new TerritoryRecord("07", "137", "BOYACA", "LA VICTORIA"),
            new TerritoryRecord("07", "139", "BOYACA", "VILLA DE LEIVA"),
            new TerritoryRecord("07", "142", "BOYACA", "MACANAL"),
            new TerritoryRecord("07", "148", "BOYACA", "MARIPI"),
            new TerritoryRecord("07", "151", "BOYACA", "MIRAFLORES"),
            new TerritoryRecord("07", "154", "BOYACA", "MONGUA"),
            new TerritoryRecord("07", "157", "BOYACA", "MONGUI"),
            new TerritoryRecord("07", "160", "BOYACA", "MONIQUIRA"),
            new TerritoryRecord("07", "161", "BOYACA", "MOTAVITA"),
            new TerritoryRecord("07", "163", "BOYACA", "MUZO"),
            new TerritoryRecord("07", "166", "BOYACA", "NOBSA"),
            new TerritoryRecord("07", "169", "BOYACA", "NUEVO COLON"),
            new TerritoryRecord("07", "173", "BOYACA", "OICATA"),
            new TerritoryRecord("07", "176", "BOYACA", "OTANCHE"),
            new TerritoryRecord("07", "178", "BOYACA", "PACHAVITA"),
            new TerritoryRecord("07", "179", "BOYACA", "PAEZ"),
            new TerritoryRecord("07", "181", "BOYACA", "PAIPA"),
            new TerritoryRecord("07", "184", "BOYACA", "PAJARITO"),
            new TerritoryRecord("07", "187", "BOYACA", "PANQUEBA"),
            new TerritoryRecord("07", "190", "BOYACA", "PAUNA"),
            new TerritoryRecord("07", "193", "BOYACA", "PAYA"),
            new TerritoryRecord("07", "199", "BOYACA", "PAZ DE RIO"),
            new TerritoryRecord("07", "202", "BOYACA", "PESCA"),
            new TerritoryRecord("07", "205", "BOYACA", "PISBA"),
            new TerritoryRecord("07", "214", "BOYACA", "PUERTO BOYACA"),
            new TerritoryRecord("07", "215", "BOYACA", "QUIPAMA"),
            new TerritoryRecord("07", "217", "BOYACA", "RAMIRIQUI"),
            new TerritoryRecord("07", "220", "BOYACA", "RAQUIRA"),
            new TerritoryRecord("07", "223", "BOYACA", "RONDON"),
            new TerritoryRecord("07", "226", "BOYACA", "SABOYA"),
            new TerritoryRecord("07", "232", "BOYACA", "SACHICA"),
            new TerritoryRecord("07", "235", "BOYACA", "SAMACA"),
            new TerritoryRecord("07", "237", "BOYACA", "SAN EDUARDO"),
            new TerritoryRecord("07", "238", "BOYACA", "SAN JOSE DE PARE"),
            new TerritoryRecord("07", "241", "BOYACA", "SAN LUIS DE GACENO"),
            new TerritoryRecord("07", "247", "BOYACA", "SAN MATEO"),
            new TerritoryRecord("07", "248", "BOYACA", "SAN MIGUEL DE SEMA"),
            new TerritoryRecord("07", "249", "BOYACA", "SAN PABLO DE BORBUR"),
            new TerritoryRecord("07", "250", "BOYACA", "SANTANA"),
            new TerritoryRecord("07", "251", "BOYACA", "SANTA MARIA"),
            new TerritoryRecord("07", "253", "BOYACA", "SANTA ROSA DE VITERBO"),
            new TerritoryRecord("07", "256", "BOYACA", "SANTA SOFIA"),
            new TerritoryRecord("07", "259", "BOYACA", "SATIVANORTE"),
            new TerritoryRecord("07", "262", "BOYACA", "SATIVASUR"),
            new TerritoryRecord("07", "265", "BOYACA", "SIACHOQUE"),
            new TerritoryRecord("07", "268", "BOYACA", "SOATA"),
            new TerritoryRecord("07", "271", "BOYACA", "SOCOTA"),
            new TerritoryRecord("07", "274", "BOYACA", "SOCHA"),
            new TerritoryRecord("07", "277", "BOYACA", "SOGAMOSO"),
            new TerritoryRecord("07", "280", "BOYACA", "SOMONDOCO"),
            new TerritoryRecord("07", "281", "BOYACA", "SORA"),
            new TerritoryRecord("07", "282", "BOYACA", "SORACA"),
            new TerritoryRecord("07", "283", "BOYACA", "SOTAQUIRA"),
            new TerritoryRecord("07", "286", "BOYACA", "SUSACON"),
            new TerritoryRecord("07", "289", "BOYACA", "SUTAMARCHAN"),
            new TerritoryRecord("07", "292", "BOYACA", "SUTATENZA"),
            new TerritoryRecord("07", "298", "BOYACA", "TASCO"),
            new TerritoryRecord("07", "301", "BOYACA", "TENZA"),
            new TerritoryRecord("07", "304", "BOYACA", "TIBANA"),
            new TerritoryRecord("07", "307", "BOYACA", "TIBASOSA"),
            new TerritoryRecord("07", "310", "BOYACA", "TINJACA"),
            new TerritoryRecord("07", "311", "BOYACA", "TIPACOQUE"),
            new TerritoryRecord("07", "313", "BOYACA", "TOCA"),
            new TerritoryRecord("07", "316", "BOYACA", "TOGUI"),
            new TerritoryRecord("07", "319", "BOYACA", "TOPAGA"),
            new TerritoryRecord("07", "322", "BOYACA", "TOTA"),
            new TerritoryRecord("07", "324", "BOYACA", "TUNUNGUA"),
            new TerritoryRecord("07", "325", "BOYACA", "TURMEQUE"),
            new TerritoryRecord("07", "328", "BOYACA", "TUTA"),
            new TerritoryRecord("07", "331", "BOYACA", "TUTAZA"),
            new TerritoryRecord("07", "334", "BOYACA", "UMBITA"),
            new TerritoryRecord("07", "337", "BOYACA", "VENTAQUEMADA"),
            new TerritoryRecord("07", "340", "BOYACA", "VIRACACHA"),
            new TerritoryRecord("07", "346", "BOYACA", "ZETAQUIRA"),
            new TerritoryRecord("09", "001", "CALDAS", "MANIZALES"),
            new TerritoryRecord("09", "004", "CALDAS", "AGUADAS"),
            new TerritoryRecord("09", "007", "CALDAS", "ANSERMA"),
            new TerritoryRecord("09", "013", "CALDAS", "ARANZAZU"),
            new TerritoryRecord("09", "022", "CALDAS", "BELALCAZAR"),
            new TerritoryRecord("09", "034", "CALDAS", "CHINCHINA"),
            new TerritoryRecord("09", "037", "CALDAS", "FILADELFIA"),
            new TerritoryRecord("09", "049", "CALDAS", "LA DORADA"),
            new TerritoryRecord("09", "052", "CALDAS", "LA MERCED"),
            new TerritoryRecord("09", "055", "CALDAS", "MANZANARES"),
            new TerritoryRecord("09", "058", "CALDAS", "MARMATO"),
            new TerritoryRecord("09", "061", "CALDAS", "MARQUETALIA"),
            new TerritoryRecord("09", "067", "CALDAS", "MARULANDA"),
            new TerritoryRecord("09", "076", "CALDAS", "NEIRA"),
            new TerritoryRecord("09", "078", "CALDAS", "NORCASIA"),
            new TerritoryRecord("09", "079", "CALDAS", "PACORA"),
            new TerritoryRecord("09", "082", "CALDAS", "PALESTINA"),
            new TerritoryRecord("09", "085", "CALDAS", "PENSILVANIA"),
            new TerritoryRecord("09", "103", "CALDAS", "RIOSUCIO"),
            new TerritoryRecord("09", "106", "CALDAS", "RISARALDA"),
            new TerritoryRecord("09", "109", "CALDAS", "SALAMINA"),
            new TerritoryRecord("09", "115", "CALDAS", "SAMANA"),
            new TerritoryRecord("09", "120", "CALDAS", "SAN JOSE"),
            new TerritoryRecord("09", "124", "CALDAS", "SUPIA"),
            new TerritoryRecord("09", "127", "CALDAS", "VICTORIA"),
            new TerritoryRecord("09", "130", "CALDAS", "VILLAMARIA"),
            new TerritoryRecord("09", "133", "CALDAS", "VITERBO"),
            new TerritoryRecord("11", "001", "CAUCA", "POPAYAN"),
            new TerritoryRecord("11", "004", "CAUCA", "ALMAGUER"),
            new TerritoryRecord("11", "005", "CAUCA", "ARGELIA"),
            new TerritoryRecord("11", "006", "CAUCA", "BALBOA"),
            new TerritoryRecord("11", "007", "CAUCA", "BOLIVAR"),
            new TerritoryRecord("11", "010", "CAUCA", "BUENOS AIRES"),
            new TerritoryRecord("11", "013", "CAUCA", "CAJIBIO"),
            new TerritoryRecord("11", "016", "CAUCA", "CALDONO"),
            new TerritoryRecord("11", "019", "CAUCA", "CALOTO"),
            new TerritoryRecord("11", "022", "CAUCA", "CORINTO"),
            new TerritoryRecord("11", "025", "CAUCA", "EL TAMBO"),
            new TerritoryRecord("11", "027", "CAUCA", "FLORENCIA"),
            new TerritoryRecord("11", "028", "CAUCA", "GUAPI"),
            new TerritoryRecord("11", "029", "CAUCA", "GUACHENE"),
            new TerritoryRecord("11", "031", "CAUCA", "INZA"),
            new TerritoryRecord("11", "034", "CAUCA", "JAMBALO"),
            new TerritoryRecord("11", "037", "CAUCA", "LA SIERRA"),
            new TerritoryRecord("11", "040", "CAUCA", "LA VEGA"),
            new TerritoryRecord("11", "043", "CAUCA", "LOPEZ (MICAY)"),
            new TerritoryRecord("11", "046", "CAUCA", "MERCADERES"),
            new TerritoryRecord("11", "049", "CAUCA", "MIRANDA"),
            new TerritoryRecord("11", "052", "CAUCA", "MORALES"),
            new TerritoryRecord("11", "053", "CAUCA", "PADILLA"),
            new TerritoryRecord("11", "055", "CAUCA", "PAEZ (BELALCAZAR)"),
            new TerritoryRecord("11", "058", "CAUCA", "PATIA (EL BORDO)"),
            new TerritoryRecord("11", "060", "CAUCA", "PIAMONTE"),
            new TerritoryRecord("11", "061", "CAUCA", "PIENDAMO"),
            new TerritoryRecord("11", "064", "CAUCA", "PUERTO TEJADA"),
            new TerritoryRecord("11", "067", "CAUCA", "PURACE (COCONUCO)"),
            new TerritoryRecord("11", "070", "CAUCA", "ROSAS"),
            new TerritoryRecord("11", "073", "CAUCA", "SAN SEBASTIAN"),
            new TerritoryRecord("11", "076", "CAUCA", "SANTANDER DE QUILICHAO"),
            new TerritoryRecord("11", "079", "CAUCA", "SANTA ROSA"),
            new TerritoryRecord("11", "082", "CAUCA", "SILVIA"),
            new TerritoryRecord("11", "085", "CAUCA", "SOTARA (PAISPAMBA)"),
            new TerritoryRecord("11", "086", "CAUCA", "SUCRE"),
            new TerritoryRecord("11", "087", "CAUCA", "SUAREZ"),
            new TerritoryRecord("11", "088", "CAUCA", "TIMBIO"),
            new TerritoryRecord("11", "091", "CAUCA", "TIMBIQUI"),
            new TerritoryRecord("11", "094", "CAUCA", "TORIBIO"),
            new TerritoryRecord("11", "097", "CAUCA", "TOTORO"),
            new TerritoryRecord("11", "098", "CAUCA", "VILLA RICA"),
            new TerritoryRecord("12", "001", "CESAR", "VALLEDUPAR"),
            new TerritoryRecord("12", "075", "CESAR", "AGUACHICA"),
            new TerritoryRecord("12", "150", "CESAR", "AGUSTIN CODAZZI"),
            new TerritoryRecord("12", "170", "CESAR", "ASTREA"),
            new TerritoryRecord("12", "180", "CESAR", "BECERRIL"),
            new TerritoryRecord("12", "200", "CESAR", "BOSCONIA"),
            new TerritoryRecord("12", "225", "CESAR", "CURUMANI"),
            new TerritoryRecord("12", "300", "CESAR", "CHIMICHAGUA"),
            new TerritoryRecord("12", "375", "CESAR", "CHIRIGUANA"),
            new TerritoryRecord("12", "410", "CESAR", "EL COPEY"),
            new TerritoryRecord("12", "415", "CESAR", "EL PASO"),
            new TerritoryRecord("12", "450", "CESAR", "GAMARRA"),
            new TerritoryRecord("12", "525", "CESAR", "GONZALEZ"),
            new TerritoryRecord("12", "600", "CESAR", "LA GLORIA"),
            new TerritoryRecord("12", "608", "CESAR", "LA JAGUA DE IBIRICO"),
            new TerritoryRecord("12", "625", "CESAR", "MANAURE BALCON DEL CESAR (MANA"),
            new TerritoryRecord("12", "650", "CESAR", "PAILITAS"),
            new TerritoryRecord("12", "700", "CESAR", "PELAYA"),
            new TerritoryRecord("12", "720", "CESAR", "PUEBLO BELLO"),
            new TerritoryRecord("12", "750", "CESAR", "RIO DE ORO"),
            new TerritoryRecord("12", "800", "CESAR", "SAN ALBERTO"),
            new TerritoryRecord("12", "825", "CESAR", "LA PAZ"),
            new TerritoryRecord("12", "850", "CESAR", "SAN DIEGO"),
            new TerritoryRecord("12", "875", "CESAR", "SAN MARTIN"),
            new TerritoryRecord("12", "900", "CESAR", "TAMALAMEQUE"),
            new TerritoryRecord("13", "001", "CORDOBA", "MONTERIA"),
            new TerritoryRecord("13", "004", "CORDOBA", "AYAPEL"),
            new TerritoryRecord("13", "007", "CORDOBA", "BUENAVISTA"),
            new TerritoryRecord("13", "009", "CORDOBA", "CANALETE"),
            new TerritoryRecord("13", "010", "CORDOBA", "CERETE"),
            new TerritoryRecord("13", "013", "CORDOBA", "CIENAGA DE ORO"),
            new TerritoryRecord("13", "014", "CORDOBA", "COTORRA (BONGO)"),
            new TerritoryRecord("13", "016", "CORDOBA", "CHIMA"),
            new TerritoryRecord("13", "019", "CORDOBA", "CHINU"),
            new TerritoryRecord("13", "020", "CORDOBA", "LA APARTADA (FRONTERA)"),
            new TerritoryRecord("13", "022", "CORDOBA", "LORICA"),
            new TerritoryRecord("13", "023", "CORDOBA", "LOS CORDOBAS"),
            new TerritoryRecord("13", "024", "CORDOBA", "MOMIL"),
            new TerritoryRecord("13", "025", "CORDOBA", "MONTELIBANO"),
            new TerritoryRecord("13", "027", "CORDOBA", "MO/ITOS"),
            new TerritoryRecord("13", "028", "CORDOBA", "PLANETA RICA"),
            new TerritoryRecord("13", "031", "CORDOBA", "PUEBLO NUEVO"),
            new TerritoryRecord("13", "032", "CORDOBA", "PUERTO LIBERTADOR"),
            new TerritoryRecord("13", "033", "CORDOBA", "PUERTO ESCONDIDO"),
            new TerritoryRecord("13", "034", "CORDOBA", "PURISIMA"),
            new TerritoryRecord("13", "037", "CORDOBA", "SAHAGUN"),
            new TerritoryRecord("13", "040", "CORDOBA", "SAN ANDRES DE SOTAVENTO"),
            new TerritoryRecord("13", "043", "CORDOBA", "SAN ANTERO"),
            new TerritoryRecord("13", "046", "CORDOBA", "SAN BERNARDO DEL VIENTO"),
            new TerritoryRecord("13", "049", "CORDOBA", "SAN CARLOS"),
            new TerritoryRecord("13", "052", "CORDOBA", "SAN JOSE DE URE"),
            new TerritoryRecord("13", "055", "CORDOBA", "SAN PELAYO"),
            new TerritoryRecord("13", "058", "CORDOBA", "TIERRALTA"),
            new TerritoryRecord("13", "060", "CORDOBA", "TUCHIN"),
            new TerritoryRecord("13", "061", "CORDOBA", "VALENCIA"),
            new TerritoryRecord("15", "004", "CUNDINAMARCA", "AGUA DE DIOS"),
            new TerritoryRecord("15", "007", "CUNDINAMARCA", "ALBAN"),
            new TerritoryRecord("15", "010", "CUNDINAMARCA", "ANAPOIMA"),
            new TerritoryRecord("15", "013", "CUNDINAMARCA", "ANOLAIMA"),
            new TerritoryRecord("15", "016", "CUNDINAMARCA", "ARBELAEZ"),
            new TerritoryRecord("15", "019", "CUNDINAMARCA", "BELTRAN"),
            new TerritoryRecord("15", "022", "CUNDINAMARCA", "BITUIMA"),
            new TerritoryRecord("15", "025", "CUNDINAMARCA", "BOJACA"),
            new TerritoryRecord("15", "029", "CUNDINAMARCA", "CABRERA"),
            new TerritoryRecord("15", "030", "CUNDINAMARCA", "CACHIPAY"),
            new TerritoryRecord("15", "031", "CUNDINAMARCA", "CAJICA"),
            new TerritoryRecord("15", "034", "CUNDINAMARCA", "CAPARRAPI"),
            new TerritoryRecord("15", "037", "CUNDINAMARCA", "CAQUEZA"),
            new TerritoryRecord("15", "040", "CUNDINAMARCA", "CARMEN DE CARUPA"),
            new TerritoryRecord("15", "043", "CUNDINAMARCA", "COGUA"),
            new TerritoryRecord("15", "046", "CUNDINAMARCA", "COTA"),
            new TerritoryRecord("15", "049", "CUNDINAMARCA", "CUCUNUBA"),
            new TerritoryRecord("15", "052", "CUNDINAMARCA", "CHAGUANI"),
            new TerritoryRecord("15", "055", "CUNDINAMARCA", "CHIA"),
            new TerritoryRecord("15", "058", "CUNDINAMARCA", "CHIPAQUE"),
            new TerritoryRecord("15", "061", "CUNDINAMARCA", "CHOACHI"),
            new TerritoryRecord("15", "064", "CUNDINAMARCA", "CHOCONTA"),
            new TerritoryRecord("15", "067", "CUNDINAMARCA", "EL COLEGIO"),
            new TerritoryRecord("15", "070", "CUNDINAMARCA", "EL PE/ON"),
            new TerritoryRecord("15", "072", "CUNDINAMARCA", "EL ROSAL"),
            new TerritoryRecord("15", "076", "CUNDINAMARCA", "FACATATIVA"),
            new TerritoryRecord("15", "079", "CUNDINAMARCA", "FOMEQUE"),
            new TerritoryRecord("15", "085", "CUNDINAMARCA", "FOSCA"),
            new TerritoryRecord("15", "088", "CUNDINAMARCA", "FUNZA"),
            new TerritoryRecord("15", "091", "CUNDINAMARCA", "FUQUENE"),
            new TerritoryRecord("15", "094", "CUNDINAMARCA", "FUSAGASUGA"),
            new TerritoryRecord("15", "097", "CUNDINAMARCA", "GACHALA"),
            new TerritoryRecord("15", "100", "CUNDINAMARCA", "GACHANCIPA"),
            new TerritoryRecord("15", "103", "CUNDINAMARCA", "GACHETA"),
            new TerritoryRecord("15", "106", "CUNDINAMARCA", "GAMA"),
            new TerritoryRecord("15", "109", "CUNDINAMARCA", "GIRARDOT"),
            new TerritoryRecord("15", "112", "CUNDINAMARCA", "GUACHETA"),
            new TerritoryRecord("15", "115", "CUNDINAMARCA", "GUADUAS"),
            new TerritoryRecord("15", "118", "CUNDINAMARCA", "GUASCA"),
            new TerritoryRecord("15", "121", "CUNDINAMARCA", "GUATAQUI"),
            new TerritoryRecord("15", "124", "CUNDINAMARCA", "GUATAVITA"),
            new TerritoryRecord("15", "127", "CUNDINAMARCA", "GUAYABAL DE SIQUIMA"),
            new TerritoryRecord("15", "128", "CUNDINAMARCA", "GUAYABETAL"),
            new TerritoryRecord("15", "130", "CUNDINAMARCA", "GUTIERREZ"),
            new TerritoryRecord("15", "132", "CUNDINAMARCA", "GRANADA"),
            new TerritoryRecord("15", "133", "CUNDINAMARCA", "JERUSALEN"),
            new TerritoryRecord("15", "136", "CUNDINAMARCA", "JUNIN"),
            new TerritoryRecord("15", "139", "CUNDINAMARCA", "LA CALERA"),
            new TerritoryRecord("15", "142", "CUNDINAMARCA", "LA MESA"),
            new TerritoryRecord("15", "145", "CUNDINAMARCA", "LA PALMA"),
            new TerritoryRecord("15", "148", "CUNDINAMARCA", "LA PE/A"),
            new TerritoryRecord("15", "151", "CUNDINAMARCA", "LA VEGA"),
            new TerritoryRecord("15", "154", "CUNDINAMARCA", "LENGUAZAQUE"),
            new TerritoryRecord("15", "157", "CUNDINAMARCA", "MACHETA"),
            new TerritoryRecord("15", "160", "CUNDINAMARCA", "MADRID"),
            new TerritoryRecord("15", "163", "CUNDINAMARCA", "MANTA"),
            new TerritoryRecord("15", "166", "CUNDINAMARCA", "MEDINA"),
            new TerritoryRecord("15", "169", "CUNDINAMARCA", "MOSQUERA"),
            new TerritoryRecord("15", "172", "CUNDINAMARCA", "NARI/O"),
            new TerritoryRecord("15", "175", "CUNDINAMARCA", "NEMOCON"),
            new TerritoryRecord("15", "178", "CUNDINAMARCA", "NILO"),
            new TerritoryRecord("15", "181", "CUNDINAMARCA", "NIMAIMA"),
            new TerritoryRecord("15", "184", "CUNDINAMARCA", "NOCAIMA"),
            new TerritoryRecord("15", "190", "CUNDINAMARCA", "PACHO"),
            new TerritoryRecord("15", "193", "CUNDINAMARCA", "PAIME"),
            new TerritoryRecord("15", "196", "CUNDINAMARCA", "PANDI"),
            new TerritoryRecord("15", "198", "CUNDINAMARCA", "PARATEBUENO (LA NAGUAYA)"),
            new TerritoryRecord("15", "199", "CUNDINAMARCA", "PASCA"),
            new TerritoryRecord("15", "202", "CUNDINAMARCA", "PUERTO SALGAR"),
            new TerritoryRecord("15", "205", "CUNDINAMARCA", "PULI"),
            new TerritoryRecord("15", "208", "CUNDINAMARCA", "QUEBRADANEGRA"),
            new TerritoryRecord("15", "211", "CUNDINAMARCA", "QUETAME"),
            new TerritoryRecord("15", "214", "CUNDINAMARCA", "QUIPILE"),
            new TerritoryRecord("15", "217", "CUNDINAMARCA", "APULO"),
            new TerritoryRecord("15", "218", "CUNDINAMARCA", "RICAURTE"),
            new TerritoryRecord("15", "220", "CUNDINAMARCA", "SAN ANTONIO DEL TEQUENDAMA"),
            new TerritoryRecord("15", "223", "CUNDINAMARCA", "SAN BERNARDO"),
            new TerritoryRecord("15", "226", "CUNDINAMARCA", "SAN CAYETANO"),
            new TerritoryRecord("15", "229", "CUNDINAMARCA", "SAN FRANCISCO"),
            new TerritoryRecord("15", "232", "CUNDINAMARCA", "SAN JUAN DE RIOSECO"),
            new TerritoryRecord("15", "235", "CUNDINAMARCA", "SASAIMA"),
            new TerritoryRecord("15", "238", "CUNDINAMARCA", "SESQUILE"),
            new TerritoryRecord("15", "239", "CUNDINAMARCA", "SIBATE"),
            new TerritoryRecord("15", "241", "CUNDINAMARCA", "SILVANIA"),
            new TerritoryRecord("15", "244", "CUNDINAMARCA", "SIMIJACA"),
            new TerritoryRecord("15", "247", "CUNDINAMARCA", "SOACHA"),
            new TerritoryRecord("15", "250", "CUNDINAMARCA", "SOPO"),
            new TerritoryRecord("15", "256", "CUNDINAMARCA", "SUBACHOQUE"),
            new TerritoryRecord("15", "259", "CUNDINAMARCA", "SUESCA"),
            new TerritoryRecord("15", "262", "CUNDINAMARCA", "SUPATA"),
            new TerritoryRecord("15", "265", "CUNDINAMARCA", "SUSA"),
            new TerritoryRecord("15", "268", "CUNDINAMARCA", "SUTATAUSA"),
            new TerritoryRecord("15", "271", "CUNDINAMARCA", "TABIO"),
            new TerritoryRecord("15", "274", "CUNDINAMARCA", "TAUSA"),
            new TerritoryRecord("15", "277", "CUNDINAMARCA", "TENA"),
            new TerritoryRecord("15", "280", "CUNDINAMARCA", "TENJO"),
            new TerritoryRecord("15", "283", "CUNDINAMARCA", "TIBACUY"),
            new TerritoryRecord("15", "286", "CUNDINAMARCA", "TIBIRITA"),
            new TerritoryRecord("15", "289", "CUNDINAMARCA", "TOCAIMA"),
            new TerritoryRecord("15", "292", "CUNDINAMARCA", "TOCANCIPA"),
            new TerritoryRecord("15", "295", "CUNDINAMARCA", "TOPAIPI"),
            new TerritoryRecord("15", "298", "CUNDINAMARCA", "UBALA"),
            new TerritoryRecord("15", "301", "CUNDINAMARCA", "UBAQUE"),
            new TerritoryRecord("15", "304", "CUNDINAMARCA", "UBATE"),
            new TerritoryRecord("15", "307", "CUNDINAMARCA", "UNE"),
            new TerritoryRecord("15", "316", "CUNDINAMARCA", "UTICA"),
            new TerritoryRecord("15", "318", "CUNDINAMARCA", "VENECIA"),
            new TerritoryRecord("15", "319", "CUNDINAMARCA", "VERGARA"),
            new TerritoryRecord("15", "322", "CUNDINAMARCA", "VIANI"),
            new TerritoryRecord("15", "323", "CUNDINAMARCA", "VILLAGOMEZ"),
            new TerritoryRecord("15", "325", "CUNDINAMARCA", "VILLAPINZON"),
            new TerritoryRecord("15", "328", "CUNDINAMARCA", "VILLETA"),
            new TerritoryRecord("15", "331", "CUNDINAMARCA", "VIOTA"),
            new TerritoryRecord("15", "334", "CUNDINAMARCA", "YACOPI"),
            new TerritoryRecord("15", "337", "CUNDINAMARCA", "ZIPACON"),
            new TerritoryRecord("15", "340", "CUNDINAMARCA", "ZIPAQUIRA"),
            new TerritoryRecord("15", "001", "CUNDINAMARCA", "BOGOTA, D.C."),
            new TerritoryRecord("16", "001", "BOGOTA", "BOGOTA, D.C."),
            new TerritoryRecord("17", "001", "CHOCO", "QUIBDO"),
            new TerritoryRecord("17", "002", "CHOCO", "ATRATO (YUTO)"),
            new TerritoryRecord("17", "004", "CHOCO", "ACANDI"),
            new TerritoryRecord("17", "006", "CHOCO", "ALTO BAUDO (PIE DE PATO)"),
            new TerritoryRecord("17", "007", "CHOCO", "BAGADO"),
            new TerritoryRecord("17", "008", "CHOCO", "BAHIA SOLANO (MUTIS)"),
            new TerritoryRecord("17", "010", "CHOCO", "BAJO BAUDO (PIZARRO)"),
            new TerritoryRecord("17", "011", "CHOCO", "BOJAYA (BELLAVISTA)"),
            new TerritoryRecord("17", "012", "CHOCO", "MEDIO ATRATO (BETE)"),
            new TerritoryRecord("17", "013", "CHOCO", "CONDOTO"),
            new TerritoryRecord("17", "014", "CHOCO", "CERTEGUI"),
            new TerritoryRecord("17", "015", "CHOCO", "CARMEN DEL DARIEN"),
            new TerritoryRecord("17", "016", "CHOCO", "EL CARMEN"),
            new TerritoryRecord("17", "017", "CHOCO", "EL CANTON DEL SAN PABLO (MAN."),
            new TerritoryRecord("17", "019", "CHOCO", "ISTMINA"),
            new TerritoryRecord("17", "022", "CHOCO", "JURADO"),
            new TerritoryRecord("17", "025", "CHOCO", "LLORO"),
            new TerritoryRecord("17", "026", "CHOCO", "MEDIO BAUDO (PUERTO MELUK)"),
            new TerritoryRecord("17", "027", "CHOCO", "MEDIO SAN JUAN"),
            new TerritoryRecord("17", "028", "CHOCO", "NOVITA"),
            new TerritoryRecord("17", "031", "CHOCO", "NUQUI"),
            new TerritoryRecord("17", "032", "CHOCO", "RIO IRO"),
            new TerritoryRecord("17", "034", "CHOCO", "RIOSUCIO"),
            new TerritoryRecord("17", "035", "CHOCO", "RIO QUITO (PAIMADO)"),
            new TerritoryRecord("17", "037", "CHOCO", "SAN JOSE DEL PALMAR"),
            new TerritoryRecord("17", "038", "CHOCO", "EL LITORAL DEL SAN JUAN"),
            new TerritoryRecord("17", "040", "CHOCO", "SIPI"),
            new TerritoryRecord("17", "043", "CHOCO", "TADO"),
            new TerritoryRecord("17", "048", "CHOCO", "UNGUIA"),
            new TerritoryRecord("17", "060", "CHOCO", "UNION PANAMERICANA (LAS ANIMAS"),
            new TerritoryRecord("19", "001", "HUILA", "NEIVA"),
            new TerritoryRecord("19", "004", "HUILA", "ACEVEDO"),
            new TerritoryRecord("19", "007", "HUILA", "AGRADO"),
            new TerritoryRecord("19", "010", "HUILA", "AIPE"),
            new TerritoryRecord("19", "013", "HUILA", "ALGECIRAS"),
            new TerritoryRecord("19", "016", "HUILA", "ALTAMIRA"),
            new TerritoryRecord("19", "019", "HUILA", "BARAYA"),
            new TerritoryRecord("19", "022", "HUILA", "CAMPOALEGRE"),
            new TerritoryRecord("19", "025", "HUILA", "TESALIA (CARNICERIAS)"),
            new TerritoryRecord("19", "028", "HUILA", "COLOMBIA"),
            new TerritoryRecord("19", "031", "HUILA", "ELIAS"),
            new TerritoryRecord("19", "034", "HUILA", "GARZON"),
            new TerritoryRecord("19", "037", "HUILA", "GIGANTE"),
            new TerritoryRecord("19", "040", "HUILA", "GUADALUPE"),
            new TerritoryRecord("19", "043", "HUILA", "HOBO"),
            new TerritoryRecord("19", "044", "HUILA", "ISNOS"),
            new TerritoryRecord("19", "046", "HUILA", "IQUIRA"),
            new TerritoryRecord("19", "047", "HUILA", "LA ARGENTINA (PLATA VIEJA)"),
            new TerritoryRecord("19", "049", "HUILA", "LA PLATA"),
            new TerritoryRecord("19", "050", "HUILA", "NATAGA"),
            new TerritoryRecord("19", "051", "HUILA", "OPORAPA"),
            new TerritoryRecord("19", "052", "HUILA", "PAICOL"),
            new TerritoryRecord("19", "055", "HUILA", "PALERMO"),
            new TerritoryRecord("19", "056", "HUILA", "PALESTINA"),
            new TerritoryRecord("19", "058", "HUILA", "PITAL"),
            new TerritoryRecord("19", "061", "HUILA", "PITALITO"),
            new TerritoryRecord("19", "064", "HUILA", "RIVERA"),
            new TerritoryRecord("19", "067", "HUILA", "SALADOBLANCO"),
            new TerritoryRecord("19", "070", "HUILA", "SAN AGUSTIN"),
            new TerritoryRecord("19", "074", "HUILA", "SANTA MARIA"),
            new TerritoryRecord("19", "076", "HUILA", "SUAZA"),
            new TerritoryRecord("19", "079", "HUILA", "TARQUI"),
            new TerritoryRecord("19", "082", "HUILA", "TELLO"),
            new TerritoryRecord("19", "085", "HUILA", "TERUEL"),
            new TerritoryRecord("19", "088", "HUILA", "TIMANA"),
            new TerritoryRecord("19", "091", "HUILA", "VILLAVIEJA"),
            new TerritoryRecord("19", "094", "HUILA", "YAGUARA"),
            new TerritoryRecord("21", "001", "MAGDALENA", "SANTA MARTA"),
            new TerritoryRecord("21", "008", "MAGDALENA", "ALGARROBO"),
            new TerritoryRecord("21", "010", "MAGDALENA", "ARACATACA"),
            new TerritoryRecord("21", "012", "MAGDALENA", "ARIGUANI (EL DIFICIL)"),
            new TerritoryRecord("21", "013", "MAGDALENA", "CERRO DE SAN ANTONIO"),
            new TerritoryRecord("21", "015", "MAGDALENA", "CHIVOLO"),
            new TerritoryRecord("21", "016", "MAGDALENA", "CIENAGA"),
            new TerritoryRecord("21", "020", "MAGDALENA", "CONCORDIA"),
            new TerritoryRecord("21", "025", "MAGDALENA", "EL BANCO"),
            new TerritoryRecord("21", "028", "MAGDALENA", "EL PI/ON"),
            new TerritoryRecord("21", "030", "MAGDALENA", "EL RETEN"),
            new TerritoryRecord("21", "031", "MAGDALENA", "FUNDACION"),
            new TerritoryRecord("21", "040", "MAGDALENA", "GUAMAL"),
            new TerritoryRecord("21", "042", "MAGDALENA", "NUEVA GRANADA"),
            new TerritoryRecord("21", "046", "MAGDALENA", "PEDRAZA"),
            new TerritoryRecord("21", "048", "MAGDALENA", "PIJI/O DEL CARMEN"),
            new TerritoryRecord("21", "049", "MAGDALENA", "PIVIJAY"),
            new TerritoryRecord("21", "052", "MAGDALENA", "PLATO"),
            new TerritoryRecord("21", "055", "MAGDALENA", "PUEBLOVIEJO"),
            new TerritoryRecord("21", "058", "MAGDALENA", "REMOLINO"),
            new TerritoryRecord("21", "060", "MAGDALENA", "SABANAS DE SAN ANGEL"),
            new TerritoryRecord("21", "067", "MAGDALENA", "SALAMINA"),
            new TerritoryRecord("21", "070", "MAGDALENA", "SAN SEBASTIAN DE BUENAVISTA"),
            new TerritoryRecord("21", "073", "MAGDALENA", "SAN ZENON"),
            new TerritoryRecord("21", "076", "MAGDALENA", "SANTA ANA"),
            new TerritoryRecord("21", "078", "MAGDALENA", "SANTA BARBARA DE PINTO"),
            new TerritoryRecord("21", "079", "MAGDALENA", "SITIONUEVO"),
            new TerritoryRecord("21", "085", "MAGDALENA", "TENERIFE"),
            new TerritoryRecord("21", "090", "MAGDALENA", "ZAPAYAN"),
            new TerritoryRecord("21", "095", "MAGDALENA", "ZONA BANANERA (SEVILLA)"),
            new TerritoryRecord("23", "001", "NARIÑO", "PASTO"),
            new TerritoryRecord("23", "004", "NARIÑO", "ALBAN (SAN JOSE)"),
            new TerritoryRecord("23", "007", "NARIÑO", "ALDANA"),
            new TerritoryRecord("23", "010", "NARIÑO", "ANCUYA"),
            new TerritoryRecord("23", "013", "NARIÑO", "ARBOLEDA (BERRUECOS)"),
            new TerritoryRecord("23", "016", "NARIÑO", "BARBACOAS"),
            new TerritoryRecord("23", "017", "NARIÑO", "BELEN"),
            new TerritoryRecord("23", "019", "NARIÑO", "BUESACO"),
            new TerritoryRecord("23", "022", "NARIÑO", "COLON (GENOVA)"),
            new TerritoryRecord("23", "025", "NARIÑO", "CONSACA"),
            new TerritoryRecord("23", "028", "NARIÑO", "CONTADERO"),
            new TerritoryRecord("23", "031", "NARIÑO", "CORDOBA"),
            new TerritoryRecord("23", "034", "NARIÑO", "CUASPUD (CARLOSAMA)"),
            new TerritoryRecord("23", "037", "NARIÑO", "CUMBAL"),
            new TerritoryRecord("23", "038", "NARIÑO", "CHACHAGUI"),
            new TerritoryRecord("23", "039", "NARIÑO", "CUMBITARA"),
            new TerritoryRecord("23", "040", "NARIÑO", "EL ROSARIO"),
            new TerritoryRecord("23", "041", "NARIÑO", "EL CHARCO"),
            new TerritoryRecord("23", "043", "NARIÑO", "EL TABLON"),
            new TerritoryRecord("23", "044", "NARIÑO", "EL PE/OL"),
            new TerritoryRecord("23", "046", "NARIÑO", "EL TAMBO"),
            new TerritoryRecord("23", "047", "NARIÑO", "FRANCISCO PIZARRO (SALAHONDA)"),
            new TerritoryRecord("23", "049", "NARIÑO", "FUNES"),
            new TerritoryRecord("23", "052", "NARIÑO", "GUACHUCAL"),
            new TerritoryRecord("23", "055", "NARIÑO", "GUAITARILLA"),
            new TerritoryRecord("23", "058", "NARIÑO", "GUALMATAN"),
            new TerritoryRecord("23", "061", "NARIÑO", "ILES"),
            new TerritoryRecord("23", "064", "NARIÑO", "IMUES"),
            new TerritoryRecord("23", "067", "NARIÑO", "IPIALES"),
            new TerritoryRecord("23", "073", "NARIÑO", "LA CRUZ"),
            new TerritoryRecord("23", "076", "NARIÑO", "LA FLORIDA"),
            new TerritoryRecord("23", "077", "NARIÑO", "LA LLANADA"),
            new TerritoryRecord("23", "078", "NARIÑO", "LA TOLA"),
            new TerritoryRecord("23", "079", "NARIÑO", "LA UNION"),
            new TerritoryRecord("23", "080", "NARIÑO", "LEIVA"),
            new TerritoryRecord("23", "082", "NARIÑO", "LINARES"),
            new TerritoryRecord("23", "085", "NARIÑO", "LOS ANDES (SOTOMAYOR)"),
            new TerritoryRecord("23", "088", "NARIÑO", "MAGUI (PAYAN)"),
            new TerritoryRecord("23", "091", "NARIÑO", "MALLAMA (PIEDRANCHA)"),
            new TerritoryRecord("23", "094", "NARIÑO", "MOSQUERA"),
            new TerritoryRecord("23", "095", "NARIÑO", "OLAYA HERRERA"),
            new TerritoryRecord("23", "096", "NARIÑO", "NARI/O"),
            new TerritoryRecord("23", "097", "NARIÑO", "OSPINA"),
            new TerritoryRecord("23", "098", "NARIÑO", "POLICARPA"),
            new TerritoryRecord("23", "100", "NARIÑO", "POTOSI"),
            new TerritoryRecord("23", "101", "NARIÑO", "PROVIDENCIA"),
            new TerritoryRecord("23", "103", "NARIÑO", "PUERRES"),
            new TerritoryRecord("23", "106", "NARIÑO", "PUPIALES"),
            new TerritoryRecord("23", "109", "NARIÑO", "RICAURTE"),
            new TerritoryRecord("23", "112", "NARIÑO", "ROBERTO PAYAN (SAN JOSE)"),
            new TerritoryRecord("23", "115", "NARIÑO", "SAMANIEGO"),
            new TerritoryRecord("23", "118", "NARIÑO", "SANDONA"),
            new TerritoryRecord("23", "120", "NARIÑO", "SAN BERNARDO"),
            new TerritoryRecord("23", "121", "NARIÑO", "SAN LORENZO"),
            new TerritoryRecord("23", "123", "NARIÑO", "SAN PEDRO DE CARTAGO"),
            new TerritoryRecord("23", "124", "NARIÑO", "SAN PABLO"),
            new TerritoryRecord("23", "125", "NARIÑO", "SANTA BARBARA (ISCUANDE)"),
            new TerritoryRecord("23", "127", "NARIÑO", "SANTACRUZ (GUACHAVES)"),
            new TerritoryRecord("23", "130", "NARIÑO", "SAPUYES"),
            new TerritoryRecord("23", "133", "NARIÑO", "TAMINANGO"),
            new TerritoryRecord("23", "136", "NARIÑO", "TANGUA"),
            new TerritoryRecord("23", "139", "NARIÑO", "TUMACO"),
            new TerritoryRecord("23", "142", "NARIÑO", "TUQUERRES"),
            new TerritoryRecord("23", "145", "NARIÑO", "YACUANQUER"),
            new TerritoryRecord("24", "001", "RISARALDA", "PEREIRA"),
            new TerritoryRecord("24", "008", "RISARALDA", "APIA"),
            new TerritoryRecord("24", "013", "RISARALDA", "BALBOA"),
            new TerritoryRecord("24", "021", "RISARALDA", "BELEN DE UMBRIA"),
            new TerritoryRecord("24", "025", "RISARALDA", "DOSQUEBRADAS"),
            new TerritoryRecord("24", "029", "RISARALDA", "GUATICA"),
            new TerritoryRecord("24", "038", "RISARALDA", "LA CELIA"),
            new TerritoryRecord("24", "046", "RISARALDA", "LA VIRGINIA"),
            new TerritoryRecord("24", "054", "RISARALDA", "MARSELLA"),
            new TerritoryRecord("24", "062", "RISARALDA", "MISTRATO"),
            new TerritoryRecord("24", "070", "RISARALDA", "PUEBLO RICO"),
            new TerritoryRecord("24", "078", "RISARALDA", "QUINCHIA"),
            new TerritoryRecord("24", "086", "RISARALDA", "SANTA ROSA DE CABAL"),
            new TerritoryRecord("24", "094", "RISARALDA", "SANTUARIO"),
            new TerritoryRecord("25", "001", "NORTE DE SANTANDER", "CUCUTA"),
            new TerritoryRecord("25", "004", "NORTE DE SANTANDER", "ABREGO"),
            new TerritoryRecord("25", "007", "NORTE DE SANTANDER", "ARBOLEDAS"),
            new TerritoryRecord("25", "010", "NORTE DE SANTANDER", "BOCHALEMA"),
            new TerritoryRecord("25", "013", "NORTE DE SANTANDER", "BUCARASICA"),
            new TerritoryRecord("25", "016", "NORTE DE SANTANDER", "CACOTA"),
            new TerritoryRecord("25", "019", "NORTE DE SANTANDER", "CACHIRA"),
            new TerritoryRecord("25", "022", "NORTE DE SANTANDER", "CONVENCION"),
            new TerritoryRecord("25", "025", "NORTE DE SANTANDER", "CUCUTILLA"),
            new TerritoryRecord("25", "028", "NORTE DE SANTANDER", "CHINACOTA"),
            new TerritoryRecord("25", "031", "NORTE DE SANTANDER", "CHITAGA"),
            new TerritoryRecord("25", "034", "NORTE DE SANTANDER", "DURANIA"),
            new TerritoryRecord("25", "036", "NORTE DE SANTANDER", "EL TARRA"),
            new TerritoryRecord("25", "037", "NORTE DE SANTANDER", "EL CARMEN"),
            new TerritoryRecord("25", "038", "NORTE DE SANTANDER", "EL ZULIA"),
            new TerritoryRecord("25", "040", "NORTE DE SANTANDER", "GRAMALOTE"),
            new TerritoryRecord("25", "043", "NORTE DE SANTANDER", "HACARI"),
            new TerritoryRecord("25", "046", "NORTE DE SANTANDER", "HERRAN"),
            new TerritoryRecord("25", "049", "NORTE DE SANTANDER", "LABATECA"),
            new TerritoryRecord("25", "051", "NORTE DE SANTANDER", "LA ESPERANZA"),
            new TerritoryRecord("25", "052", "NORTE DE SANTANDER", "LA PLAYA"),
            new TerritoryRecord("25", "054", "NORTE DE SANTANDER", "LOS PATIOS"),
            new TerritoryRecord("25", "055", "NORTE DE SANTANDER", "LOURDES"),
            new TerritoryRecord("25", "058", "NORTE DE SANTANDER", "MUTISCUA"),
            new TerritoryRecord("25", "061", "NORTE DE SANTANDER", "OCA/A"),
            new TerritoryRecord("25", "064", "NORTE DE SANTANDER", "PAMPLONA"),
            new TerritoryRecord("25", "067", "NORTE DE SANTANDER", "PAMPLONITA"),
            new TerritoryRecord("25", "069", "NORTE DE SANTANDER", "PUERTO SANTANDER"),
            new TerritoryRecord("25", "070", "NORTE DE SANTANDER", "RAGONVALIA"),
            new TerritoryRecord("25", "073", "NORTE DE SANTANDER", "SALAZAR"),
            new TerritoryRecord("25", "076", "NORTE DE SANTANDER", "SAN CALIXTO"),
            new TerritoryRecord("25", "079", "NORTE DE SANTANDER", "SAN CAYETANO"),
            new TerritoryRecord("25", "082", "NORTE DE SANTANDER", "SANTIAGO"),
            new TerritoryRecord("25", "085", "NORTE DE SANTANDER", "SARDINATA"),
            new TerritoryRecord("25", "088", "NORTE DE SANTANDER", "SILOS"),
            new TerritoryRecord("25", "091", "NORTE DE SANTANDER", "TEORAMA"),
            new TerritoryRecord("25", "093", "NORTE DE SANTANDER", "TIBU"),
            new TerritoryRecord("25", "094", "NORTE DE SANTANDER", "TOLEDO"),
            new TerritoryRecord("25", "097", "NORTE DE SANTANDER", "VILLA CARO"),
            new TerritoryRecord("25", "100", "NORTE DE SANTANDER", "VILLA DEL ROSARIO"),
            new TerritoryRecord("26", "001", "QUINDIO", "ARMENIA"),
            new TerritoryRecord("26", "005", "QUINDIO", "BUENAVISTA"),
            new TerritoryRecord("26", "010", "QUINDIO", "CALARCA"),
            new TerritoryRecord("26", "020", "QUINDIO", "CIRCASIA"),
            new TerritoryRecord("26", "025", "QUINDIO", "CORDOBA"),
            new TerritoryRecord("26", "030", "QUINDIO", "FILANDIA"),
            new TerritoryRecord("26", "040", "QUINDIO", "GENOVA"),
            new TerritoryRecord("26", "050", "QUINDIO", "LA TEBAIDA"),
            new TerritoryRecord("26", "060", "QUINDIO", "MONTENEGRO"),
            new TerritoryRecord("26", "070", "QUINDIO", "PIJAO"),
            new TerritoryRecord("26", "080", "QUINDIO", "QUIMBAYA"),
            new TerritoryRecord("26", "090", "QUINDIO", "SALENTO"),
            new TerritoryRecord("27", "001", "SANTANDER", "BUCARAMANGA"),
            new TerritoryRecord("27", "004", "SANTANDER", "AGUADA"),
            new TerritoryRecord("27", "007", "SANTANDER", "ALBANIA"),
            new TerritoryRecord("27", "010", "SANTANDER", "ARATOCA"),
            new TerritoryRecord("27", "013", "SANTANDER", "BARBOSA"),
            new TerritoryRecord("27", "016", "SANTANDER", "BARICHARA"),
            new TerritoryRecord("27", "019", "SANTANDER", "BARRANCABERMEJA"),
            new TerritoryRecord("27", "022", "SANTANDER", "BETULIA"),
            new TerritoryRecord("27", "025", "SANTANDER", "BOLIVAR"),
            new TerritoryRecord("27", "028", "SANTANDER", "CABRERA"),
            new TerritoryRecord("27", "031", "SANTANDER", "CALIFORNIA"),
            new TerritoryRecord("27", "034", "SANTANDER", "CAPITANEJO"),
            new TerritoryRecord("27", "037", "SANTANDER", "CARCASI"),
            new TerritoryRecord("27", "040", "SANTANDER", "CEPITA"),
            new TerritoryRecord("27", "043", "SANTANDER", "CERRITO"),
            new TerritoryRecord("27", "045", "SANTANDER", "CIMITARRA"),
            new TerritoryRecord("27", "046", "SANTANDER", "CONCEPCION"),
            new TerritoryRecord("27", "049", "SANTANDER", "CONFINES"),
            new TerritoryRecord("27", "052", "SANTANDER", "CONTRATACION"),
            new TerritoryRecord("27", "055", "SANTANDER", "COROMORO"),
            new TerritoryRecord("27", "058", "SANTANDER", "CURITI"),
            new TerritoryRecord("27", "061", "SANTANDER", "CHARALA"),
            new TerritoryRecord("27", "064", "SANTANDER", "CHARTA"),
            new TerritoryRecord("27", "067", "SANTANDER", "CHIMA"),
            new TerritoryRecord("27", "070", "SANTANDER", "CHIPATA"),
            new TerritoryRecord("27", "071", "SANTANDER", "EL CARMEN"),
            new TerritoryRecord("27", "073", "SANTANDER", "EL GUACAMAYO"),
            new TerritoryRecord("27", "074", "SANTANDER", "EL PLAYON"),
            new TerritoryRecord("27", "075", "SANTANDER", "EL PE/ON"),
            new TerritoryRecord("27", "076", "SANTANDER", "ENCINO"),
            new TerritoryRecord("27", "079", "SANTANDER", "ENCISO"),
            new TerritoryRecord("27", "080", "SANTANDER", "FLORIAN"),
            new TerritoryRecord("27", "082", "SANTANDER", "FLORIDABLANCA"),
            new TerritoryRecord("27", "085", "SANTANDER", "GALAN"),
            new TerritoryRecord("27", "088", "SANTANDER", "GAMBITA"),
            new TerritoryRecord("27", "091", "SANTANDER", "GIRON"),
            new TerritoryRecord("27", "094", "SANTANDER", "GUACA"),
            new TerritoryRecord("27", "097", "SANTANDER", "GUADALUPE"),
            new TerritoryRecord("27", "100", "SANTANDER", "GUAPOTA"),
            new TerritoryRecord("27", "103", "SANTANDER", "GUAVATA"),
            new TerritoryRecord("27", "106", "SANTANDER", "GUEPSA"),
            new TerritoryRecord("27", "109", "SANTANDER", "HATO"),
            new TerritoryRecord("27", "112", "SANTANDER", "JESUS MARIA"),
            new TerritoryRecord("27", "115", "SANTANDER", "JORDAN"),
            new TerritoryRecord("27", "118", "SANTANDER", "LA PAZ"),
            new TerritoryRecord("27", "119", "SANTANDER", "LA BELLEZA"),
            new TerritoryRecord("27", "120", "SANTANDER", "LANDAZURI"),
            new TerritoryRecord("27", "121", "SANTANDER", "LEBRIJA"),
            new TerritoryRecord("27", "124", "SANTANDER", "LOS SANTOS"),
            new TerritoryRecord("27", "127", "SANTANDER", "MACARAVITA"),
            new TerritoryRecord("27", "130", "SANTANDER", "MALAGA"),
            new TerritoryRecord("27", "133", "SANTANDER", "MATANZA"),
            new TerritoryRecord("27", "136", "SANTANDER", "MOGOTES"),
            new TerritoryRecord("27", "139", "SANTANDER", "MOLAGAVITA"),
            new TerritoryRecord("27", "142", "SANTANDER", "OCAMONTE"),
            new TerritoryRecord("27", "145", "SANTANDER", "OIBA"),
            new TerritoryRecord("27", "148", "SANTANDER", "ONZAGA"),
            new TerritoryRecord("27", "151", "SANTANDER", "PALMAR"),
            new TerritoryRecord("27", "154", "SANTANDER", "PALMAS DEL SOCORRO"),
            new TerritoryRecord("27", "157", "SANTANDER", "PARAMO"),
            new TerritoryRecord("27", "160", "SANTANDER", "PIEDECUESTA"),
            new TerritoryRecord("27", "163", "SANTANDER", "PINCHOTE"),
            new TerritoryRecord("27", "166", "SANTANDER", "PUENTE NACIONAL"),
            new TerritoryRecord("27", "167", "SANTANDER", "PUERTO PARRA"),
            new TerritoryRecord("27", "169", "SANTANDER", "PUERTO WILCHES"),
            new TerritoryRecord("27", "172", "SANTANDER", "RIONEGRO"),
            new TerritoryRecord("27", "174", "SANTANDER", "SABANA DE TORRES"),
            new TerritoryRecord("27", "175", "SANTANDER", "SAN ANDRES"),
            new TerritoryRecord("27", "178", "SANTANDER", "SAN BENITO"),
            new TerritoryRecord("27", "181", "SANTANDER", "SAN GIL"),
            new TerritoryRecord("27", "184", "SANTANDER", "SAN JOAQUIN"),
            new TerritoryRecord("27", "187", "SANTANDER", "SAN JOSE DE MIRANDA"),
            new TerritoryRecord("27", "190", "SANTANDER", "SAN MIGUEL"),
            new TerritoryRecord("27", "193", "SANTANDER", "SAN VICENTE DE CHUCURI"),
            new TerritoryRecord("27", "194", "SANTANDER", "SANTA HELENA DEL OPON"),
            new TerritoryRecord("27", "195", "SANTANDER", "SANTA BARBARA"),
            new TerritoryRecord("27", "196", "SANTANDER", "SIMACOTA"),
            new TerritoryRecord("27", "199", "SANTANDER", "SOCORRO"),
            new TerritoryRecord("27", "202", "SANTANDER", "SUAITA"),
            new TerritoryRecord("27", "205", "SANTANDER", "SUCRE"),
            new TerritoryRecord("27", "208", "SANTANDER", "SURATA"),
            new TerritoryRecord("27", "211", "SANTANDER", "TONA"),
            new TerritoryRecord("27", "217", "SANTANDER", "VALLE DE SAN JOSE"),
            new TerritoryRecord("27", "219", "SANTANDER", "VETAS"),
            new TerritoryRecord("27", "220", "SANTANDER", "VELEZ"),
            new TerritoryRecord("27", "221", "SANTANDER", "VILLANUEVA"),
            new TerritoryRecord("27", "223", "SANTANDER", "ZAPATOCA"),
            new TerritoryRecord("28", "001", "SUCRE", "SINCELEJO"),
            new TerritoryRecord("28", "010", "SUCRE", "BUENAVISTA"),
            new TerritoryRecord("28", "020", "SUCRE", "CAIMITO"),
            new TerritoryRecord("28", "030", "SUCRE", "COLOSO (RICAURTE)"),
            new TerritoryRecord("28", "040", "SUCRE", "COROZAL"),
            new TerritoryRecord("28", "041", "SUCRE", "COVE/AS"),
            new TerritoryRecord("28", "042", "SUCRE", "EL ROBLE"),
            new TerritoryRecord("28", "045", "SUCRE", "CHALAN"),
            new TerritoryRecord("28", "048", "SUCRE", "GALERAS (NUEVA GRANADA)"),
            new TerritoryRecord("28", "049", "SUCRE", "GUARANDA"),
            new TerritoryRecord("28", "050", "SUCRE", "LA UNION"),
            new TerritoryRecord("28", "055", "SUCRE", "LOS PALMITOS"),
            new TerritoryRecord("28", "060", "SUCRE", "MAJAGUAL"),
            new TerritoryRecord("28", "080", "SUCRE", "MORROA"),
            new TerritoryRecord("28", "100", "SUCRE", "OVEJAS"),
            new TerritoryRecord("28", "120", "SUCRE", "PALMITO"),
            new TerritoryRecord("28", "160", "SUCRE", "SAMPUES"),
            new TerritoryRecord("28", "180", "SUCRE", "SAN BENITO ABAD"),
            new TerritoryRecord("28", "190", "SUCRE", "SAN JUAN DE BETULIA (BETULIA)"),
            new TerritoryRecord("28", "200", "SUCRE", "SAN MARCOS"),
            new TerritoryRecord("28", "220", "SUCRE", "SAN ONOFRE"),
            new TerritoryRecord("28", "240", "SUCRE", "SAN PEDRO"),
            new TerritoryRecord("28", "260", "SUCRE", "SINCE"),
            new TerritoryRecord("28", "280", "SUCRE", "SUCRE"),
            new TerritoryRecord("28", "300", "SUCRE", "TOLU"),
            new TerritoryRecord("28", "320", "SUCRE", "TOLUVIEJO"),
            new TerritoryRecord("29", "001", "TOLIMA", "IBAGUE"),
            new TerritoryRecord("29", "004", "TOLIMA", "ALPUJARRA"),
            new TerritoryRecord("29", "007", "TOLIMA", "ALVARADO"),
            new TerritoryRecord("29", "010", "TOLIMA", "AMBALEMA"),
            new TerritoryRecord("29", "013", "TOLIMA", "ANZOATEGUI"),
            new TerritoryRecord("29", "016", "TOLIMA", "ARMERO (GUAYABAL)"),
            new TerritoryRecord("29", "019", "TOLIMA", "ATACO"),
            new TerritoryRecord("29", "022", "TOLIMA", "CAJAMARCA"),
            new TerritoryRecord("29", "025", "TOLIMA", "CARMEN DE APICALA"),
            new TerritoryRecord("29", "028", "TOLIMA", "CASABIANCA"),
            new TerritoryRecord("29", "031", "TOLIMA", "COELLO"),
            new TerritoryRecord("29", "034", "TOLIMA", "COYAIMA"),
            new TerritoryRecord("29", "037", "TOLIMA", "CUNDAY"),
            new TerritoryRecord("29", "040", "TOLIMA", "CHAPARRAL"),
            new TerritoryRecord("29", "043", "TOLIMA", "DOLORES"),
            new TerritoryRecord("29", "046", "TOLIMA", "ESPINAL"),
            new TerritoryRecord("29", "049", "TOLIMA", "FALAN"),
            new TerritoryRecord("29", "052", "TOLIMA", "FLANDES"),
            new TerritoryRecord("29", "055", "TOLIMA", "FRESNO"),
            new TerritoryRecord("29", "058", "TOLIMA", "GUAMO"),
            new TerritoryRecord("29", "061", "TOLIMA", "HERVEO"),
            new TerritoryRecord("29", "064", "TOLIMA", "HONDA"),
            new TerritoryRecord("29", "067", "TOLIMA", "ICONONZO"),
            new TerritoryRecord("29", "070", "TOLIMA", "LERIDA"),
            new TerritoryRecord("29", "073", "TOLIMA", "LIBANO"),
            new TerritoryRecord("29", "076", "TOLIMA", "MARIQUITA"),
            new TerritoryRecord("29", "079", "TOLIMA", "MELGAR"),
            new TerritoryRecord("29", "080", "TOLIMA", "MURILLO"),
            new TerritoryRecord("29", "082", "TOLIMA", "NATAGAIMA"),
            new TerritoryRecord("29", "085", "TOLIMA", "ORTEGA"),
            new TerritoryRecord("29", "087", "TOLIMA", "PALOCABILDO"),
            new TerritoryRecord("29", "088", "TOLIMA", "PIEDRAS"),
            new TerritoryRecord("29", "089", "TOLIMA", "PLANADAS"),
            new TerritoryRecord("29", "091", "TOLIMA", "PRADO"),
            new TerritoryRecord("29", "094", "TOLIMA", "PURIFICACION"),
            new TerritoryRecord("29", "097", "TOLIMA", "RIOBLANCO"),
            new TerritoryRecord("29", "100", "TOLIMA", "RONCESVALLES"),
            new TerritoryRecord("29", "103", "TOLIMA", "ROVIRA"),
            new TerritoryRecord("29", "105", "TOLIMA", "SALDA/A"),
            new TerritoryRecord("29", "106", "TOLIMA", "SAN ANTONIO"),
            new TerritoryRecord("29", "109", "TOLIMA", "SAN LUIS"),
            new TerritoryRecord("29", "112", "TOLIMA", "SANTA ISABEL"),
            new TerritoryRecord("29", "115", "TOLIMA", "SUAREZ"),
            new TerritoryRecord("29", "118", "TOLIMA", "VALLE DE SAN JUAN"),
            new TerritoryRecord("29", "121", "TOLIMA", "VENADILLO"),
            new TerritoryRecord("29", "124", "TOLIMA", "VILLAHERMOSA"),
            new TerritoryRecord("29", "127", "TOLIMA", "VILLARRICA"),
            new TerritoryRecord("31", "001", "VALLE", "CALI"),
            new TerritoryRecord("31", "004", "VALLE", "ALCALA"),
            new TerritoryRecord("31", "007", "VALLE", "ANDALUCIA"),
            new TerritoryRecord("31", "010", "VALLE", "ANSERMANUEVO"),
            new TerritoryRecord("31", "013", "VALLE", "ARGELIA"),
            new TerritoryRecord("31", "016", "VALLE", "BOLIVAR"),
            new TerritoryRecord("31", "019", "VALLE", "BUENAVENTURA"),
            new TerritoryRecord("31", "022", "VALLE", "BUGA"),
            new TerritoryRecord("31", "025", "VALLE", "BUGALAGRANDE"),
            new TerritoryRecord("31", "028", "VALLE", "CAICEDONIA"),
            new TerritoryRecord("31", "031", "VALLE", "CANDELARIA"),
            new TerritoryRecord("31", "034", "VALLE", "CARTAGO"),
            new TerritoryRecord("31", "037", "VALLE", "DAGUA"),
            new TerritoryRecord("31", "040", "VALLE", "CALIMA (DARIEN)"),
            new TerritoryRecord("31", "043", "VALLE", "EL AGUILA"),
            new TerritoryRecord("31", "046", "VALLE", "EL CAIRO"),
            new TerritoryRecord("31", "049", "VALLE", "EL CERRITO"),
            new TerritoryRecord("31", "052", "VALLE", "EL DOVIO"),
            new TerritoryRecord("31", "055", "VALLE", "FLORIDA"),
            new TerritoryRecord("31", "058", "VALLE", "GINEBRA"),
            new TerritoryRecord("31", "061", "VALLE", "GUACARI"),
            new TerritoryRecord("31", "064", "VALLE", "JAMUNDI"),
            new TerritoryRecord("31", "067", "VALLE", "LA CUMBRE"),
            new TerritoryRecord("31", "070", "VALLE", "LA UNION"),
            new TerritoryRecord("31", "073", "VALLE", "LA VICTORIA"),
            new TerritoryRecord("31", "076", "VALLE", "OBANDO"),
            new TerritoryRecord("31", "079", "VALLE", "PALMIRA"),
            new TerritoryRecord("31", "082", "VALLE", "PRADERA"),
            new TerritoryRecord("31", "085", "VALLE", "RESTREPO"),
            new TerritoryRecord("31", "088", "VALLE", "RIOFRIO"),
            new TerritoryRecord("31", "091", "VALLE", "ROLDANILLO"),
            new TerritoryRecord("31", "094", "VALLE", "SAN PEDRO"),
            new TerritoryRecord("31", "097", "VALLE", "SEVILLA"),
            new TerritoryRecord("31", "100", "VALLE", "TORO"),
            new TerritoryRecord("31", "103", "VALLE", "TRUJILLO"),
            new TerritoryRecord("31", "106", "VALLE", "TULUA"),
            new TerritoryRecord("31", "109", "VALLE", "ULLOA"),
            new TerritoryRecord("31", "112", "VALLE", "VERSALLES"),
            new TerritoryRecord("31", "115", "VALLE", "VIJES"),
            new TerritoryRecord("31", "118", "VALLE", "YOTOCO"),
            new TerritoryRecord("31", "121", "VALLE", "YUMBO"),
            new TerritoryRecord("31", "124", "VALLE", "ZARZAL"),
            new TerritoryRecord("40", "001", "ARAUCA", "ARAUCA"),
            new TerritoryRecord("40", "005", "ARAUCA", "TAME"),
            new TerritoryRecord("40", "010", "ARAUCA", "ARAUQUITA"),
            new TerritoryRecord("40", "015", "ARAUCA", "CRAVO NORTE"),
            new TerritoryRecord("40", "017", "ARAUCA", "FORTUL"),
            new TerritoryRecord("40", "020", "ARAUCA", "PUERTO RONDON"),
            new TerritoryRecord("40", "025", "ARAUCA", "SARAVENA"),
            new TerritoryRecord("44", "001", "CAQUETA", "FLORENCIA"),
            new TerritoryRecord("44", "002", "CAQUETA", "ALBANIA"),
            new TerritoryRecord("44", "003", "CAQUETA", "CARTAGENA DEL CHAIRA"),
            new TerritoryRecord("44", "004", "CAQUETA", "BELEN DE LOS ANDAQUIES"),
            new TerritoryRecord("44", "005", "CAQUETA", "EL DONCELLO"),
            new TerritoryRecord("44", "006", "CAQUETA", "EL PAUJIL"),
            new TerritoryRecord("44", "007", "CAQUETA", "LA MONTA/ITA"),
            new TerritoryRecord("44", "009", "CAQUETA", "PUERTO RICO"),
            new TerritoryRecord("44", "010", "CAQUETA", "SAN VICENTE DEL CAGUAN"),
            new TerritoryRecord("44", "012", "CAQUETA", "CURILLO"),
            new TerritoryRecord("44", "016", "CAQUETA", "MILAN"),
            new TerritoryRecord("44", "017", "CAQUETA", "MORELIA"),
            new TerritoryRecord("44", "020", "CAQUETA", "SAN JOSE DEL FRAGUA"),
            new TerritoryRecord("44", "022", "CAQUETA", "SOLANO"),
            new TerritoryRecord("44", "024", "CAQUETA", "SOLITA"),
            new TerritoryRecord("44", "040", "CAQUETA", "VALPARAISO"),
            new TerritoryRecord("46", "001", "CASANARE", "YOPAL"),
            new TerritoryRecord("46", "040", "CASANARE", "AGUAZUL"),
            new TerritoryRecord("46", "120", "CASANARE", "CHAMEZA"),
            new TerritoryRecord("46", "320", "CASANARE", "HATO COROZAL"),
            new TerritoryRecord("46", "480", "CASANARE", "LA SALINA"),
            new TerritoryRecord("46", "520", "CASANARE", "MANI"),
            new TerritoryRecord("46", "540", "CASANARE", "MONTERREY"),
            new TerritoryRecord("46", "560", "CASANARE", "NUNCHIA"),
            new TerritoryRecord("46", "640", "CASANARE", "OROCUE"),
            new TerritoryRecord("46", "680", "CASANARE", "PAZ DE ARIPORO (MORENO)"),
            new TerritoryRecord("46", "700", "CASANARE", "PORE"),
            new TerritoryRecord("46", "760", "CASANARE", "RECETOR"),
            new TerritoryRecord("46", "800", "CASANARE", "SABANALARGA"),
            new TerritoryRecord("46", "815", "CASANARE", "SACAMA"),
            new TerritoryRecord("46", "830", "CASANARE", "SAN LUIS DE PALENQUE"),
            new TerritoryRecord("46", "840", "CASANARE", "TAMARA"),
            new TerritoryRecord("46", "850", "CASANARE", "TAURAMENA"),
            new TerritoryRecord("46", "865", "CASANARE", "TRINIDAD"),
            new TerritoryRecord("46", "880", "CASANARE", "VILLANUEVA"),
            new TerritoryRecord("48", "001", "LA GUAJIRA", "RIOHACHA"),
            new TerritoryRecord("48", "002", "LA GUAJIRA", "ALBANIA"),
            new TerritoryRecord("48", "004", "LA GUAJIRA", "BARRANCAS"),
            new TerritoryRecord("48", "005", "LA GUAJIRA", "DIBULLA"),
            new TerritoryRecord("48", "006", "LA GUAJIRA", "EL MOLINO"),
            new TerritoryRecord("48", "007", "LA GUAJIRA", "FONSECA"),
            new TerritoryRecord("48", "008", "LA GUAJIRA", "DISTRACCION"),
            new TerritoryRecord("48", "009", "LA GUAJIRA", "HATONUEVO"),
            new TerritoryRecord("48", "010", "LA GUAJIRA", "MAICAO"),
            new TerritoryRecord("48", "011", "LA GUAJIRA", "MANAURE"),
            new TerritoryRecord("48", "012", "LA GUAJIRA", "LA JAGUA DEL PILAR"),
            new TerritoryRecord("48", "013", "LA GUAJIRA", "SAN JUAN DEL CESAR"),
            new TerritoryRecord("48", "016", "LA GUAJIRA", "URIBIA"),
            new TerritoryRecord("48", "018", "LA GUAJIRA", "URUMITA"),
            new TerritoryRecord("48", "020", "LA GUAJIRA", "VILLANUEVA"),
            new TerritoryRecord("50", "001", "GUAINIA", "INIRIDA"),
            new TerritoryRecord("50", "050", "GUAINIA", "MAPIRIPANA"),
            new TerritoryRecord("50", "070", "GUAINIA", "BARRANCO MINAS"),
            new TerritoryRecord("50", "073", "GUAINIA", "CACAHUAL"),
            new TerritoryRecord("50", "078", "GUAINIA", "LA GUADALUPE"),
            new TerritoryRecord("50", "083", "GUAINIA", "MORICHAL (MORICHAL NUEVO)"),
            new TerritoryRecord("50", "087", "GUAINIA", "PANA PANA (CAMPO ALEGRE)"),
            new TerritoryRecord("50", "090", "GUAINIA", "PUERTO COLOMBIA"),
            new TerritoryRecord("50", "092", "GUAINIA", "SAN FELIPE"),
            new TerritoryRecord("52", "001", "META", "VILLAVICENCIO"),
            new TerritoryRecord("52", "005", "META", "ACACIAS"),
            new TerritoryRecord("52", "006", "META", "BARRANCA DE UPIA"),
            new TerritoryRecord("52", "008", "META", "CABUYARO"),
            new TerritoryRecord("52", "010", "META", "CASTILLA LA NUEVA"),
            new TerritoryRecord("52", "015", "META", "CUBARRAL"),
            new TerritoryRecord("52", "020", "META", "CUMARAL"),
            new TerritoryRecord("52", "025", "META", "EL CALVARIO"),
            new TerritoryRecord("52", "027", "META", "EL CASTILLO"),
            new TerritoryRecord("52", "028", "META", "EL DORADO"),
            new TerritoryRecord("52", "030", "META", "FUENTE DE ORO"),
            new TerritoryRecord("52", "035", "META", "GRANADA"),
            new TerritoryRecord("52", "040", "META", "GUAMAL"),
            new TerritoryRecord("52", "041", "META", "LA MACARENA"),
            new TerritoryRecord("52", "042", "META", "LEJANIAS"),
            new TerritoryRecord("52", "043", "META", "PUERTO GAITAN"),
            new TerritoryRecord("52", "044", "META", "MESETAS"),
            new TerritoryRecord("52", "045", "META", "PUERTO LOPEZ"),
            new TerritoryRecord("52", "046", "META", "MAPIRIPAN"),
            new TerritoryRecord("52", "047", "META", "PUERTO CONCORDIA"),
            new TerritoryRecord("52", "048", "META", "PUERTO LLERAS"),
            new TerritoryRecord("52", "049", "META", "PUERTO RICO"),
            new TerritoryRecord("52", "050", "META", "RESTREPO"),
            new TerritoryRecord("52", "055", "META", "SAN CARLOS DE GUAROA"),
            new TerritoryRecord("52", "058", "META", "SAN JUAN DE ARAMA"),
            new TerritoryRecord("52", "059", "META", "SAN JUANITO"),
            new TerritoryRecord("52", "060", "META", "SAN MARTIN DE LOS LLANOS"),
            new TerritoryRecord("52", "074", "META", "URIBE"),
            new TerritoryRecord("52", "080", "META", "VISTA HERMOSA"),
            new TerritoryRecord("54", "001", "GUAVIARE", "SAN JOSE DEL GUAVIARE"),
            new TerritoryRecord("54", "003", "GUAVIARE", "CALAMAR"),
            new TerritoryRecord("54", "007", "GUAVIARE", "EL RETORNO"),
            new TerritoryRecord("54", "012", "GUAVIARE", "MIRAFLORES"),
            new TerritoryRecord("56", "001", "SAN ANDRES", "SAN ANDRES"),
            new TerritoryRecord("56", "004", "SAN ANDRES", "PROVIDENCIA"),
            new TerritoryRecord("60", "001", "AMAZONAS", "LETICIA"),
            new TerritoryRecord("60", "007", "AMAZONAS", "PUERTO NARI/O"),
            new TerritoryRecord("60", "010", "AMAZONAS", "EL ENCANTO"),
            new TerritoryRecord("60", "013", "AMAZONAS", "LA CHORRERA"),
            new TerritoryRecord("60", "016", "AMAZONAS", "LA PEDRERA"),
            new TerritoryRecord("60", "017", "AMAZONAS", "LA VICTORIA"),
            new TerritoryRecord("60", "019", "AMAZONAS", "MIRITI PARANA"),
            new TerritoryRecord("60", "021", "AMAZONAS", "PUERTO SANTANDER"),
            new TerritoryRecord("60", "022", "AMAZONAS", "TARAPACA"),
            new TerritoryRecord("60", "030", "AMAZONAS", "PUERTO ALEGRIA"),
            new TerritoryRecord("60", "040", "AMAZONAS", "PUERTO ARICA"),
            new TerritoryRecord("64", "001", "PUTUMAYO", "MOCOA"),
            new TerritoryRecord("64", "002", "PUTUMAYO", "PUERTO ASIS"),
            new TerritoryRecord("64", "004", "PUTUMAYO", "PUERTO LEGUIZAMO"),
            new TerritoryRecord("64", "007", "PUTUMAYO", "COLON"),
            new TerritoryRecord("64", "013", "PUTUMAYO", "SAN FRANCISCO"),
            new TerritoryRecord("64", "016", "PUTUMAYO", "SANTIAGO"),
            new TerritoryRecord("64", "018", "PUTUMAYO", "SAN MIGUEL (LA DORADA)"),
            new TerritoryRecord("64", "019", "PUTUMAYO", "SIBUNDOY"),
            new TerritoryRecord("64", "023", "PUTUMAYO", "ORITO"),
            new TerritoryRecord("64", "025", "PUTUMAYO", "PUERTO GUZMAN"),
            new TerritoryRecord("64", "026", "PUTUMAYO", "PUERTO CAICEDO"),
            new TerritoryRecord("64", "028", "PUTUMAYO", "VALLE DEL GUAMUEZ (LA HORMIGA)"),
            new TerritoryRecord("64", "030", "PUTUMAYO", "VILLAGARZON"),
            new TerritoryRecord("68", "001", "VAUPES", "MITU"),
            new TerritoryRecord("68", "004", "VAUPES", "CARURU"),
            new TerritoryRecord("68", "010", "VAUPES", "MORICHAL (PAPUNAGUA)"),
            new TerritoryRecord("68", "013", "VAUPES", "BUENOS AIRES (PACOA)"),
            new TerritoryRecord("68", "017", "VAUPES", "TARAIRA"),
            new TerritoryRecord("68", "022", "VAUPES", "YAVARATE"),
            new TerritoryRecord("72", "001", "VICHADA", "PUERTO CARRE/O"),
            new TerritoryRecord("72", "002", "VICHADA", "SANTA ROSALIA"),
            new TerritoryRecord("72", "006", "VICHADA", "CUMARIBO"),
            new TerritoryRecord("72", "008", "VICHADA", "LA PRIMAVERA"),
            new TerritoryRecord("88", "120", "CONSULADOS", "ALEMANIA"),
            new TerritoryRecord("88", "140", "CONSULADOS", "PAISES BAJ‐ANTILLAS HOLANDESAS"),
            new TerritoryRecord("88", "155", "CONSULADOS", "ARGENTINA"),
            new TerritoryRecord("88", "160", "CONSULADOS", "PAISES BAJOS ‐ ARUBA"),
            new TerritoryRecord("88", "165", "CONSULADOS", "AUSTRALIA"),
            new TerritoryRecord("88", "170", "CONSULADOS", "AUSTRIA"),
            new TerritoryRecord("88", "185", "CONSULADOS", "BARBADOS"),
            new TerritoryRecord("88", "190", "CONSULADOS", "BELGICA"),
            new TerritoryRecord("88", "195", "CONSULADOS", "BELICE"),
            new TerritoryRecord("88", "215", "CONSULADOS", "BOLIVIA"),
            new TerritoryRecord("88", "220", "CONSULADOS", "BRASIL"),
            new TerritoryRecord("88", "250", "CONSULADOS", "CANADA"),
            new TerritoryRecord("88", "275", "CONSULADOS", "COREA DEL SUR"),
            new TerritoryRecord("88", "285", "CONSULADOS", "COSTA RICA"),
            new TerritoryRecord("88", "290", "CONSULADOS", "CUBA"),
            new TerritoryRecord("88", "300", "CONSULADOS", "CHECOSLOVAQUIA"),
            new TerritoryRecord("88", "305", "CONSULADOS", "CHILE"),
            new TerritoryRecord("88", "315", "CONSULADOS", "CHINA REPUBLICA POPULAR"),
            new TerritoryRecord("88", "320", "CONSULADOS", "CHIPRE"),
            new TerritoryRecord("88", "325", "CONSULADOS", "DINAMARCA"),
            new TerritoryRecord("88", "330", "CONSULADOS", "ECUADOR"),
            new TerritoryRecord("88", "335", "CONSULADOS", "EGIPTO"),
            new TerritoryRecord("88", "340", "CONSULADOS", "EL SALVADOR"),
            new TerritoryRecord("88", "355", "CONSULADOS", "ESPA/A"),
            new TerritoryRecord("88", "360", "CONSULADOS", "ESTADOS UNIDOS"),
            new TerritoryRecord("88", "370", "CONSULADOS", "FILIPINAS"),
            new TerritoryRecord("88", "375", "CONSULADOS", "FINLANDIA"),
            new TerritoryRecord("88", "380", "CONSULADOS", "FRANCIA"),
            new TerritoryRecord("88", "405", "CONSULADOS", "GRECIA"),
            new TerritoryRecord("88", "410", "CONSULADOS", "GUATEMALA"),
            new TerritoryRecord("88", "425", "CONSULADOS", "GUYANA"),
            new TerritoryRecord("88", "430", "CONSULADOS", "HAITI"),
            new TerritoryRecord("88", "435", "CONSULADOS", "HOLANDA"),
            new TerritoryRecord("88", "440", "CONSULADOS", "HONDURAS"),
            new TerritoryRecord("88", "450", "CONSULADOS", "HUNGRIA REPUBLICA POPULAR"),
            new TerritoryRecord("88", "455", "CONSULADOS", "INDIA"),
            new TerritoryRecord("88", "460", "CONSULADOS", "INDONESIA"),
            new TerritoryRecord("88", "465", "CONSULADOS", "INGLATERRA"),
            new TerritoryRecord("88", "475", "CONSULADOS", "IRAN"),
            new TerritoryRecord("88", "480", "CONSULADOS", "IRLANDA"),
            new TerritoryRecord("88", "490", "CONSULADOS", "ISRAEL"),
            new TerritoryRecord("88", "495", "CONSULADOS", "ITALIA"),
            new TerritoryRecord("88", "500", "CONSULADOS", "JAMAICA"),
            new TerritoryRecord("88", "505", "CONSULADOS", "JAPON"),
            new TerritoryRecord("88", "515", "CONSULADOS", "KENIA"),
            new TerritoryRecord("88", "535", "CONSULADOS", "LIBANO"),
            new TerritoryRecord("88", "560", "CONSULADOS", "MALASIA"),
            new TerritoryRecord("88", "580", "CONSULADOS", "MARRUECOS"),
            new TerritoryRecord("88", "590", "CONSULADOS", "MEXICO"),
            new TerritoryRecord("88", "620", "CONSULADOS", "NICARAGUA"),
            new TerritoryRecord("88", "635", "CONSULADOS", "NORUEGA"),
            new TerritoryRecord("88", "655", "CONSULADOS", "PANAMA"),
            new TerritoryRecord("88", "665", "CONSULADOS", "PARAGUAY"),
            new TerritoryRecord("88", "670", "CONSULADOS", "PERU"),
            new TerritoryRecord("88", "675", "CONSULADOS", "POLONIA"),
            new TerritoryRecord("88", "680", "CONSULADOS", "PORTUGAL"),
            new TerritoryRecord("88", "683", "CONSULADOS", "PUERTO RICO"),
            new TerritoryRecord("88", "685", "CONSULADOS", "REPUBLICA DOMINICANA"),
            new TerritoryRecord("88", "695", "CONSULADOS", "RUMANIA REPUBLICA SOCIAL"),
            new TerritoryRecord("88", "700", "CONSULADOS", "RUSIA"),
            new TerritoryRecord("88", "745", "CONSULADOS", "SUDAFRICA"),
            new TerritoryRecord("88", "755", "CONSULADOS", "SUECIA"),
            new TerritoryRecord("88", "760", "CONSULADOS", "SUIZA"),
            new TerritoryRecord("88", "770", "CONSULADOS", "TURQUIA"),
            new TerritoryRecord("88", "785", "CONSULADOS", "TRINIDAD Y TOBAGO"),
            new TerritoryRecord("88", "805", "CONSULADOS", "URUGUAY"),
            new TerritoryRecord("88", "815", "CONSULADOS", "VENEZUELA")
        };
    }
}